cogs5e/initTracker.py
cogs5e/models/character.py
cogs5e/models/monster.py
cogs5e/sheets/beyond.py
utils/functions.py

Resolves AFR-115, AVR-106, AVR-107, AVR-109, and DDB-001

dev: jul 25

---

.bandit
CODE_OF_CONDUCT.md
LICENSE
cogs5e/funcs/sheetFuncs.py
cogs5e/sheetManager.py
cogsmisc/customization.py

fixes issue with not dealing damage

dev: jul 31-2

---

cogs5e/homebrew.py

bugfix: critterdb

---

cogs5e/funcs/sheetFuncs.py
cogs5e/sheetManager.py

Probably wrong, but I feel like I'm learning at the very least?

`-miss` arg for attacks

---

README.md
cogs5e/charGen.py
cogs5e/dice.py
cogs5e/gametrack.py
cogs5e/homebrew.py
cogs5e/initTracker.py
cogs5e/lookup.py
cogs5e/models/dicecloudClient.py
cogs5e/pbpUtils.py
cogs5e/sheetManager.py
cogsmisc/adminUtils.py
cogsmisc/core.py
cogsmisc/customization.py
cogsmisc/permissions.py
cogsmisc/publicity.py
cogsmisc/repl.py
cogsmisc/stats.py
dbot.py
utils/help.py

- added local running docs
- edited cog framework

dev: aug 3

---

cogs5e/pbpUtils.py
cogsmisc/customization.py

dev: aug 7-2

---

cogs5e/lookup.py

Fix embed error when race has no ability score

---

cogs5e/funcs/scripting.py

Adds additional optional parameters to vroll that multiply the dice like it were a crit or add additional dice to the roll
I'm not really sure why I added the additional dice part. I only meant to do the multiply. 🤷‍♂️

Added multiply/add arg to vroll

---

cogs5e/charGen.py

Just added total at the end of randchar.
Also a typo because it bothered me?

Total added to randchar

---

cogs5e/charGen.py
cogs5e/funcs/lookupFuncs.py
cogs5e/lookup.py
cogs5e/models/background.py
cogs5e/models/race.py
utils/functions.py

Resolves #260
Resolves #236
Resolves #186
Resolves #194

Data refactors for GGR/DMM

---

cogs5e/funcs/lookupFuncs.py
cogs5e/gametrack.py
cogs5e/homebrew.py
cogs5e/initTracker.py
cogs5e/lookup.py
cogs5e/models/character.py
cogs5e/models/homebrew/tome.py
cogs5e/models/spell.py
cogs5e/sheetManager.py
cogs5e/sheets/beyond.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py
notes/dbIndices.txt
notes/homebrew/tome.spec.json

Homebrew Spell Implementation

---

cogs5e/sheets/beyond.py

I also hate DDB

---

cogs5e/charGen.py

https://cdn.discordapp.com/attachments/269276476023635978/525136758149742613/unknown.png
https://cdn.discordapp.com/attachments/269276476023635978/525137030158614538/AvraeBug.png

Fixes Background being goofed in randchar

---

cogs5e/gametrack.py

Sort spells

---

cogsmisc/core.py
dbot.py

Removes the `!donate` command, links to donations in `!about` and `!help`, and an old Patreon reward.

[DDBADB-8] Remove Donate Links

---

cogs5e/dice.py
cogs5e/funcs/scripting/combat.py
cogs5e/gametrack.py
cogs5e/homebrew.py
cogs5e/initTracker.py
cogs5e/models/character.py
cogs5e/models/dicecloud/integration.py
cogs5e/models/initiative.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py

Fixes multiple various bugs.
- AVR-303 #579 
- AVR-306 #583 
- AVR-307 #584 
- AVR-312 #597 
- AVR-320 #614 
- AVR-323 #617 
- error on some commands when characters had null spell attacks
- error that made it impossible for monsters to make checks with different skill bases
- error when syncing used counters to Dicecloud

Bugfixes - June Week 1

---

cogs5e/funcs/scripting/evaluators.py

Adds a create_cc function which acts like create_cc_nx except in that if the cc already exists, it will be replaced and if it does not already exist, created.

Added create_cc function to scripting

---

cogsmisc/customization.py

Adds `!tembed`, an embed version of `!test`

---

.github/pull_request_template.md
cogs5e/funcs/scripting/evaluators.py
cogs5e/homebrew.py
cogs5e/initTracker.py
cogs5e/models/initiative.py
cogs5e/models/spell.py
cogs5e/sheets/beyond.py
cogsmisc/adminUtils.py
cogsmisc/core.py
cogsmisc/customization.py
cogsmisc/repl.py
dbot.py
utils/checks.py
utils/functions.py

Resolves #638 
Resolves #644 
Resolves #652 
Resolves #656
Resolves #651

Fixes: 2019w26

---

cogs5e/sheetManager.py

Hope I did this right, my local copy isn't updated past the character rewrite.

Add reliable talent as a csetting

---

cogs5e/gametrack.py

[AVR-341] Fix temp hp not displaying in !g status

---

cogs5e/lookup.py

Only displays class resources if the value isn't 0.
Resolves #672

Hide resources with a value of 0 in Class lookup

---

cogs5e/initTracker.py
cogsmisc/core.py
cogsmisc/stats.py
dbot.py
notes/dbIndices.txt

This change implements some interesting statistic logging, namely:
- how many times each command has been run, and when the last run was
- how many users have run commands, when they last did, and how many
- how many unique members, servers, and commands are called over time
Resolves #690
- *note - database collections have been added and indices will need to be created*

[GH-690] initial analytics

---

.dockerignore
cogs5e/charGen.py
cogs5e/funcs/lookupFuncs.py
cogs5e/funcs/lookup_ml.py
cogs5e/lookup.py
cogs5e/sheets/beyond.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py
cogsmisc/adminUtils.py
dbot.py
migrators/import_json.py
test/sheets/autogsheet.py
tests/utils.py

Use MongoDB as the source of compendium data

✨ Mongo compendium data, automatic reloading

---

Dockerfile

Download AWS pubkey on build

---

.travis.yml
scripts/ecr_push.sh

Sets up Travis CI to deploy on tag release, and enables deploy script.

Setup Avrae bot deploy

---

cogs5e/models/homebrew/bestiary.py
cogs5e/sheets/gsheet.py

Fixes: 2019w30

---

cogs5e/dice.py
cogs5e/funcs/lookupFuncs.py
cogs5e/initTracker.py
cogs5e/lookup.py
cogsmisc/core.py
cogsmisc/stats.py
notes/dbIndices.txt
utils/functions.py

Fixes a bug in the latest unpublished release (important for deploying to AWS) involving an error when a search partially matches only one result, and moves statistics to MongoDB

Misc fixes/migrations for AWS

---

cogs5e/sheets/beyond.py

Resolves #708 - the AC calculation cannot be easily fixed until #619's new API is implemented

AVR-360 fix certain DDB stats sometimes being imported incorrectly

---

Dockerfile
cogs5e/funcs/lookupFuncs.py
dbot.py
docker/readme.md
newrelic.ini
requirements.txt
utils/newrelic.py

Adds New Relic integration to allow us to track slow commands, and also accurately blame Discord when their API is being terrible. This involves some moderate levels of awfulness (monkey patching libraries out of our control to add instrumentation).

✨ Add New Relic integration

---

cogs5e/sheetManager.py

Renames gsheet 1.3 to 1.4 in the help. Also Zhu change the name of the file on gsheet.
I offered this PR to Silverbass, so he could double the amount of code changes he had, but he forgot how to github.

Gsheet 1.3 => 1.4

---

dbot.py
utils/newrelic.py

Fix several issues with New Relic integration:
- Don't try to start a new NR transaction if one is already running. Hopefully at some point they work out some better support for coroutines.
- Don't rely on import side effects, this is generally a bad idea

Newrelic updates

---

cogs5e/funcs/lookupFuncs.py
cogs5e/homebrew.py
cogs5e/initTracker.py
cogs5e/lookup.py
cogs5e/models/homebrew/pack.py
cogs5e/sheets/beyond.py

Fixes #720 
Fixes #713 
Fixes #711 
Fixes #700

Fixes: 2019w31

---

cogs5e/funcs/lookupFuncs.py
cogs5e/gametrack.py
cogs5e/sheetManager.py
cogs5e/sheets/gsheet.py
dbot.py
requirements.txt
utils/functions.py

Who would have thought pygsheets would introduce a segfault? This PR changes pygsheets to gspread, a more mature Google Spreadsheets library, and updates the gsheet importer to require less requests.
Resolves #719 
- Replaces the pygsheets library with gspread.

Use gspread instead of pygsheets

---

utils/newrelic.py

Fixes various small issues with New Relic function naming/tracking.

New Relic continues

---

Dockerfile

Change Dockerfile to use a Python 3.7 image.

Python 3.7

---

cogs5e/funcs/scripting/evaluators.py

Tell it to commit changes
Resolves #749

AVR-381 Fix mod_hp()

---

cogs5e/dice.py
cogs5e/initTracker.py
cogs5e/models/automation.py
cogs5e/sheetManager.py
tests/cogs5e/sheetManager_test.py
tests/conftest.py

Adds some extra polish to the attack refactor.
- Makes display of iterated attacks (-rr) neater in and out of target context
- Adds some basic tests

Attack Refactor Polish

---

Dockerfile.test
cogs5e/charGen.py
cogs5e/gametrack.py
cogs5e/models/character.py
cogs5e/models/initiative.py
cogs5e/models/sheet/attack.py
cogs5e/models/sheet/player.py
cogs5e/sheets/beyond.py
cogsmisc/customization.py
cogsmisc/stats.py
requirements.txt
tests/conftest.py
tests/utiltests/argparser_test.py
utils/argparser.py
utils/help.py

Here's a hefty fix list.
**Bot Fixes/Improvements**
Resolves #731
Resolves #732 
Resolves #738 
Resolves #742 
**Command Fixes/Improvements**
Resolves #736 
Resolves #740 
Resolves #744 
Resolves #752 
**DDB Sheet Import Fixes**
Resolves #737 
Resolves #741
Resolves #695
Resolves #589 
Resolves #748 
Resolves #747 
Resolves #746 
Resolves #743 
- Makes apostrophes invalid quotes in argparse()
- Renames `Character.evaluate_cvar()` to `.evaluate_math()` and changes to use a MathEvaluator

Fixes: 2019w34

---

cogs5e/gametrack.py
cogs5e/models/automation.py
cogs5e/models/spell.py
tests/cogs5e/gametrack_test.py
tests/cogs5e/sheetManager_test.py
tests/conftest.py

Last two hotfixes for Chromatic Blue, hopefully.
Resolves #758 
Resolves #759

Hotfix: 2019w34c

---

cogs5e/dice.py
cogs5e/funcs/scripting/evaluators.py
cogs5e/gametrack.py
cogs5e/initTracker.py
cogs5e/models/automation.py
cogs5e/models/character.py
cogs5e/models/sheet/spellcasting.py
cogs5e/sheetManager.py
cogs5e/sheets/abc.py
cogs5e/sheets/beyond.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py
notes/shared.spec.ts
tests/cogs5e/dice_test.py
tests/cogs5e/gametrack_test.py
tests/utils.py

Most of this week's changes are minor QoL / display improvements.
- improved the output of `!g lr` / `!g sr`
- Resolves #799 
- readded `-mc` argument to player checks
- added support for explicitly tracking a character's spellcasting ability mod
- Changed the return type of `Character.long_rest()`, `.short_rest()`, `.on_hp()`, and `.reset_consumables()` to return `List[Tuple[CustomCounter, int]]`

2019w38: Minor QoL changes

---

cogsmisc/stats.py
notes/dbIndices.txt

Adds command usage metrics for guilds, total number of characters to date, and combat statistics to date. These will be transformed into a per-day metric by a lambda script.

add additional metrics

---

cogs5e/initTracker.py
cogs5e/models/automation.py
cogs5e/models/initiative.py
cogs5e/models/monster.py
cogs5e/models/sheet/attack.py
utils/functions.py

This PR fixes most known bugs introduced in v1.2.0.
- Fixes #847 
- Fixes #851 
- Fixes #845 
- Fixes #846 
- Fixes #833 
- Fixes some unreported bugs (Sentry: `AVRAE-BOT-33`, `AVRAE-BOT-32`, `AVRAE-BOT-30`, `AVRAE-BOT-39`, `AVRAE-BOT-2Z`, `AVRAE-BOT-2Y`)

Fixes: 2019w41

---

.gitignore
.travis.yml
Dockerfile
dbot.py
scripts/README.md
scripts/deploy.sh
scripts/sentry_release.sh

Adds a script that tags each push to master (nightly) or deploy to prod with a Sentry release.
- build steps, anyway - will let travis run the sentry steps

Add Sentry release integration

---

cogs5e/funcs/lookupFuncs.py
cogs5e/lookup.py
cogs5e/models/embeds.py
migrators/import_json.py

Resolves #801
Changes the old !rule and !condition commands to a new single command to quickly reference actions/bonus actions/conditions/other rules.
- removed `compendium.rules` and `compendium.conditions`, added `compendium.rule_references` (**requires data import**)

AFR-426 rewrite rule/condition command

---

cogs5e/funcs/scripting/combat.py
cogs5e/initTracker.py
cogs5e/lookup.py
cogs5e/models/automation.py
cogs5e/models/embeds.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/initiative.py
cogs5e/sheets/dicecloud.py
docs/automation.rst

Resolves #882 
Resolves #840 
Resolves #894 
Resolves #898 
Resolves #901 
Resolves #780

Fixes: 2019w46

---

cogs5e/sheets/gsheet.py

On the next version of the gsheet, it includes Vulnerabilities in the Resistances section. This change pulls them in, and also checks the new and old column for Immunities.
- [ x] This PR adds a new feature that is not an open feature request.

Adds support for vulnerabilities on the gsheet

---

cogs5e/models/sheet/statblock.py

Nom nom nom. Eat all the spaces so there will be no cvars created with spaces in them.
- [x ] This PR adds a new feature that is not an open feature request.

Removes spaces in imported ClassLevels

---

docs/cheatsheets/dm_combat.rst
docs/cheatsheets/pc_combat.rst
docs/index.rst

Adding combat cheatsheets to readthedocs.  
- [x ] This PR adds a new feature that is not an open feature request.
- [ x] This PR is not a code change (e.g. documentation, README, ...)

Add Cheatsheets to RTD.

---

cogs5e/funcs/lookupFuncs.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/monster.py

Adds support for spellbook tracking in newly-imported homebrew monsters. Related to #790. 
To see the actual logic changes, see [this commit](https://github.com/avrae/avrae/commit/51e5d366cc00e4fe5518323f6009c50be76df347).

Homebrew monster casting

---

cogs5e/sheets/gsheet.py

Updates the cell checked for JoAT since I moved it in 2.1. Then added a bit so it will apply the JoAT bonus, and also global "bonus to all ability checks" bonuses, from 2.0 onward (like Beyond does). And then changed a few == to >=
- [x ] This PR adds a new feature that is not an open feature request.

Apply JoAT to ability checks.

---

cogs5e/funcs/scripting/evaluators.py
cogs5e/funcs/scripting/functions.py
cogs5e/funcs/scripting/helpers.py
cogs5e/models/automation.py
cogs5e/models/character.py
cogs5e/sheets/dicecloud.py
requirements.txt
utils/argparser.py

Merging the first implementation of the Draconic interpreter (the new alias scripting handler, which was pulled out into its own repo) into nightly to test.
See https://github.com/avrae/draconic for implementation of the interpreter.

Merge Draconic 2.alpha1 into Nightly

---

cogs5e/dice.py
cogs5e/funcs/scripting/__init__.py
cogs5e/funcs/scripting/evaluators.py
cogs5e/funcs/scripting/functions.py
cogs5e/models/automation.py
cogs5e/models/initiative.py
cogs5e/models/sheet/resistance.py
cogs5e/sheetManager.py
docs/aliasing/api.rst
utils/dice.py

Pulls the Draconic 2 scripting engine into Nightly to test. This build is a production release candidate.
...when I fix the build, that is. Weird. After lunch!

Nightly: Draconic 2 Test 2

---

cogs5e/charGen.py
cogs5e/funcs/scripting/functions.py
cogs5e/funcs/scripting/legacy.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/sheet/resistance.py
utils/dice.py

*She took the midnight train, going anywhere...*
Fixes a collection of small miscellaneous issues related to the 2.0 release. Scheduled for release midnight PDT.
- removed old attribute from races in chargen
- fixed issue where arguments in the homebrew monster factory did not correspond to the right arguments in the monster constructor
- fixed some issues related to empty resistances
- ensured `Character.get_raw().resists` is a list of str (reverts an unintended breaking change)
Resolves #1055

2020w19: Midnight Fixes

---

README.md
cogs5e/sheetManager.py
cogs5e/sheets/abc.py
cogs5e/sheets/beyond.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py
utils/config.py

Rewrites the DDB sheet import to hit the character computation lambda instead of using a homebrewed rules engine implementation.
**Prerequisite to Merge**: Deploy TF update to set lambda endpt env var
- makes custom counter imports on by default for DDB and Dicecloud sheets (use `-nocc` to turn off)
- actions with saves in DDB sheets now create automation for the save correctly
Closes all issues in the linked milestone:
Fixes #619 
Fixes #1105 
Fixes #1100 
Fixes #1072 
Fixes #1039 
Fixes #1009 
Fixes #1007 
Fixes #998 
Fixes #991 
Fixes #956 
Fixes #946 
Fixes #916 
Fixes #868 
Fixes #776 
Fixes #930 
Fixes #895 
Fixes #693 
Fixes #864 
Fixes #812 
Fixes #778 
Fixes #789 
Fixes #896 
Fixes #782 
Fixes #734 
Fixes #914 
Fixes #1071 
Fixes #1052 
Fixes #1076 
Fixes #1082 
Fixes #1092 …

Rewrite DDB sheet import

---

gamedata/compendium.py

Resolves #1078
As it turns out, the framework to handle this correctly was already there but I never populated it correctly.
Oops.

AVR-550 fix entitlements type of subrace race features

---

gamedata/compendium.py
gamedata/shared.py
tests/static/compendium/srd-classes.json

AVR-565 handle class feature options in lookup

---

cogs5e/funcs/scripting/helpers.py
cogsmisc/customization.py
notes/dbIndices.txt

This adds logging each time an alias is invoked.
Log entry schema:
```typescript
{
// the type of invocation
type: "alias" | "servalias" | "snippet" | "servsnippet";
// the id of the alias/snippet being invoked
object_id: ObjectId;
// the timestamp of the invocation
timestamp: Date;
}
```
- get_snippets and get_servsnippets now return the snippet object instead of just the code - the respective commands have been updated to handle this

Log alias invocation events

---

cogs5e/initTracker.py

AVR-631 fix issue in allowed_mentions in !init opt

---

cogs5e/gametrack.py
tests/cogs5e/gametrack_test.py

Shows changes to CC value with `!cc`
When using `!cc ... set` will show delta between old and new value
Resolves #1202

Show changes when modifying CC values and add CC testing

---

cogs5e/models/sheet/attack.py

Sorts all attacks alphabetically instead of in order of the DB.
Resolves #1235 (AFR-618)

Sort iterator for attack list str generator

---

utils/help.py

Adds a footer to `!help` explaining mandatory/optional arguments
Resolves #1243 (AFR-625)

Add argument footer to help page.

---

aliasing/evaluators.py

Add a `default` arg to `get_svar()`
Resolves #1281 (AFR-644)

Add default argument to get_svar

---

cogs5e/initTracker.py
cogs5e/lookup.py
cogs5e/models/automation.py
cogs5e/models/embeds.py
cogs5e/models/errors.py
cogs5e/models/initiative.py
cogsmisc/customization.py
utils/functions.py

This hotfix fixes two major bugs introduced in v2.5.2. It is intended for release ASAP (either midnight or tomorrow).
- fixes very long alias docs not displaying correctly
- improves how text that does not fit in one embed field is chunked, fixing a lot of formatting
- fixes private messages not being sent to controllers of private combatants (introduced by intents)
- fixes certain combatants being skipped in combat (introduced by #1287)

hotfix: 2020w41

---

.gitattributes

Adds a `.gitattributes` file to the repo.
Credit to Croebh for the idea
Template taken from [this generator](https://richienb.github.io/gitattributes-generator)

Add gitattributes to repository

---

aliasing/api/combat.py

Summary
------
Updates `SimpleCombatant.effects` on `add_effect` and `remove_effect`
Adds background function `SimpleCombatant._update_effects()` so we aren't repeating ourselves.
Checklist
-------

Update effects when effects are added

---

aliasing/api/character.py
cogs5e/gametrack.py
cogs5e/models/sheet/player.py

Summary
======
Adds a description and title to custom counters/consumables
In the title, `[name]` is replaced with the character name and `[cname]` is replace with the custom counter name.
Resolves #1276 (AFR-639)
Methods added
----
`AliasCustomCounter` -
* `AliasCustomCounter.title`
* `AliasCustomCounter.desc`
`CustomCounter` -
* `CustomCounter.title`
* `CustomCounter.desc`
Checklist
======

Add description and title to consumables

---

cogs5e/dice.py

Resolves #1316 
Updates the Roll help section to include more complete information and examples.
I am not certain I have done this correctly, nor how to test it myself. My attempts to read the instructions there have failed thus far. So expect changes may be required.

Update roll help

---

aliasing/api/character.py

Adds `AliasCharacter.death_saves` to the documentation.

Add AliasCharacter death saves to documentation

---

cogs5e/lookup.py
gamedata/compendium.py
gamedata/klass.py
gamedata/lookuputils.py
notes/workshop-tags.txt
tests/static/compendium/srd-classes.json

Adds support for looking up Optional Class Features through `!classfeat` and `!class`. OCFs will only be displayed in `!class` if the user has the required entitlements.

TCoE: Optional Class Features

---

cogs5e/pbpUtils.py

With recommended changes
Fixes AFR-702. Moved from "Update pbputils.py"

Fixes AFR-702

---

docker/readme.md

`DISCORD_BOT_TOKEN` is correct here
Fix error in env file example with var name

Fix error in env file example

---

docs/aliasing/aliasing_tut.rst

Updating the alias tutorials on the website to drac2. The first (orc-relentless) required more updating to replace deprecated methods with the character( ) equivalents. The second (insult) is mostly intact but swapped the {{ }} syntax for a <drac2></drac2> code block to demonstrate other options for beginning aliasers. orc-relentless was left witht he {{ }} syntax to not overcomplicate it with indentation.

Updating Alias tutorials to Drac2

---

docs/automation_ref.rst

Updates Automation notes for lastCounterName to mention the supported way to get Spell Level.

Updates Automation notes for lastCounterName

---

aliasing/api/statblock.py
tests/aliasing/statblock_test.py

Resolves #1500 
Adding support for the <, > and == operators in the aliasskill class.

adding <, > and == for the aliasskill

---

cogs5e/sheetManager.py

Resolves #1228
I had someone adding brackets around their url and discord was hiding them from view, making it hard to tell what was wrong. Seems like a pretty easy user error to avoid, we just allow brackets around the url. I'm told I can't test it myself since I won't have access to D&D beyond with a local copy, so hopefully you guys have a unit test or something.

AFR-614 Automatically remove <> on URLs

---

README.md

Missed the reference to discord bot token was here as well.

Update to match docker/readme.md

---

cogs5e/gametrack.py

Add-Dice-Rolling-to-cc-modify

---

cogs5e/initTracker.py

Adds roll string handling for `!init madd -n`
Resolves AFR-815

Adds rollstring for -n, uses existing errors

---

cogsmisc/customization.py
utils/functions.py

Updates confirm to allow for required responses, letting it be used for cases where a specific message must be used to continue.

Add required confirm, update deletealls

---

cogs5e/sheetManager.py

Convert other instances of confirms to use the function instead of in-place code.

Converts sheet checks to use confirm

---

cogs5e/sheetManager.py
cogs5e/sheets/dicecloud.py

Adds a unified sheet importing that discovers the correct sheet type to parse with.

Adds unified sheet import

---

aliasing/api/combat.py

Resolves AFR-830
Adds ! and link to commands page for add_effect

Adds ! and link to commands page for add_effect

---

cogs5e/pbpUtils.py
cogs5e/sheetManager.py
cogsmisc/customization.py
docs/aliasing/api.rst

Split cvar tables to reduce visual noise. Updates documentation on the -color paran of tembed and embed

Add additional info on color, break up cvar tables

---

cogs5e/initTracker.py
cogs5e/models/automation/effects/damage.py
cogs5e/models/initiative/effect.py
cogs5e/utils/help_constants.py
tests/cogs5e/initTracker_test.py

#1544 adding silvered arg and adding silvered arg in `init effect` for completeness
I have tested this on my local copy to the best of my ability but I don't know how to write tests for this, if someone could help with that it would be appreciated.

Adding the silvered arg

---

aliasing/api/combat.py
cogs5e/lookup.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/initiative/combatant.py
gamedata/monster.py

Resolves #1292
Makes Monster Name available and adds Creature Type to monsters
Likely needs tests, and possible missed areas.

Monster Name now available, adds Creature Type

---

cogs5e/initTracker.py

Resolves #1358 
Adds new commands for rolling check or save as another combatant. Final names\aliases not determined yet.

Adds offturncheck and offturnsave

---

cogs5e/initTracker.py
cogs5e/models/initiative/effect.py
cogs5e/sheetManager.py
cogs5e/utils/checkutils.py

Adds `-cb` as a Check Bonus to `init effect` as well as making `!check` init aware for bonuses like `!save`

Adds check bonus, makes !check init aware

---

utils/argparser.py

Resolves AVR-801
Argparse is getting a UserList not a List, so handle both just in case

Argparse is getting a UserList not a List

---

aliasing/api/combat.py

Fixes the rtype documentation not having newline between it and description causing bad formatting on site.

Fix Documentation for Creature_Type and friends in SimpleCombatant

---

cogs5e/sheets/gsheet.py

Use unformatted value HP reading.
Resolves #AVR-805

Use unformatted value in hp

---

.github/workflows/lint-pr.yml
.github/workflows/lint.yml
.github/workflows/test.yml
cogs5e/models/automation/results.py
gamedata/compendium.py

Adds linting with annotations to new PRs.

PR Linting

---

cogs5e/sheetManager.py

Csettings help made no mention of `reset` param unless you passed something invalid.

Update CSettings documentation

---

cogs5e/models/automation/effects/attack.py
cogs5e/models/automation/runtime.py
cogs5e/sheetManager.py

Resolves #AFR-798
Add ignorecrit setting to target/character, only read if the target is a character.

Add ignorecrit setting to target/character

---

aliasing/workshop.py
cogsmisc/customization.py

Add unsubscribe for workshop aliases, move the regex for workshop to workshop.py
Resolves #AFR-834

Add Unsub, Move re for Workshop

---

cogsmisc/customization.py

A possibly poorly thought through implementation of adding newlines to multiline.

Allows newlines in multiline

---

tests/conftest.py
tests/mixed/initiative_mixed_test.py
tests/static/char-drakro.json
tests/utils.py

Update Tests for init
Give Drakro a real (Dagger), Handle Resistance in Dice Pattern

Update Init Tests to not Skip

---

aliasing/api/combat.py
cogs5e/initTracker.py
cogs5e/models/initiative/combat.py

Adds a metadata dict to SimpleCombat, useful for storing info about the combat without a placeholder.

Add SimpleCombat Metadata

---

cogs5e/models/automation/effects/damage.py

Let critdice args be added together allowing it to come from multiple snippets.

Use Sum for critdice as arg

---

cogsmisc/customization.py

Adds color, use existing vars for the making of STAT_VAR_NAMES

Add color to Snippet/Alias name check

---

cogs5e/pbpUtils.py

Update docs for techo to show timeout range

Update docs for techo to show timeout range

---

cogs5e/models/automation/effects/usecounter.py
tests/cogs5e/models/automation/effects_test.py
tests/conftest.py

Resolves #AVR-810 (Maybe)
If resources ignored, still set counter name from passed counter.

Counters Set lastCounterName on i

---

cogs5e/sheetManager.py

fix minor typo

---

cogs5e/models/character.py
cogs5e/pbpUtils.py
cogs5e/utils/actionutils.py
cogs5e/utils/checkutils.py
gamedata/spell.py
utils/functions.py

Resolves #AVR-811
Prevents error on empty `-thumb <image>` by returning blank if the var doesn't exist

Prevent error on empty -thumb image

---

cogs5e/utils/actionutils.py
cogs5e/utils/help_constants.py
gamedata/spell.py

Add verb replace to Attack

---

cogs5e/sheetManager.py

It puts the notes and sheet types in the proper order.

proper order take 2

---

.github/workflows/test.yml
aliasing/api/context.py
cogs5e/gamelog.py
cogs5e/models/automation/effects/usecounter.py
cogs5e/models/embeds.py
cogs5e/models/initiative/combat.py
cogs5e/models/initiative/effect.py
cogsmisc/core.py
cogsmisc/tutorials/__init__.py
dbot.py
ddb/gamelog/client.py
requirements.txt
tests/conftest.py
tests/requirements.txt
tests/setup.py
tests/utils.py
utils/help.py

This updates the version of discord.py from `1.7.3` to the `master` branch of the `avrae/discord.py` fork (2.0.0a3575).
- Added support for Discord threads
- Updated tests with new mock data for Discord API v8
- Misc refactors to keep up with library breaking changes

Bump discord.py

---

cogs5e/models/character.py
cogs5e/sheetManager.py
tests/utils.py
utils/context.py

Resolves #363 
Added new commands to SheetManager to handle server side characters, as well as modifying Character() to handle the new variable within the mdb.

AFR-220: Set character per server

---

cogs5e/homebrew.py
cogs5e/initTracker.py
cogsmisc/customization.py

Resolves #1591 
Implements role names into help commands where missing or relevant

#1591   show actual dm role names in the help of commands

---

cogs5e/gamelog/character.py
cogs5e/models/character.py
cogsmisc/customization.py
ui/charsettings.py
ui/menu.py
ui/servsettings.py
utils/settings/character.py

- Adds the Character Sync menu to `!csettings` to control inbound/outbound sync; available options are determined by sheet type and feature flag
- Improves the radio behaviour of buttons in the Inline Rolling menu
- Adds `!servsettings` as the entrypoint to the Server Settings menu
Merging into nightly for public test

Settings Menus: Character Sync, Radio

---

cogs5e/lookup.py
cogs5e/sheetManager.py

docs: update settings commands docs

---

cogs5e/initTracker.py

Fixes an extra `
- [ x] This PR fixes an issue.

Begone, extra `

---

Dockerfile
requirements.txt

Setting up Datadog Instrumentation

Adding for Datadog Instrumentation

---

.github/workflows/lint-pr.yml
.github/workflows/test.yml
Dockerfile
Dockerfile.ci
tests/requirements.txt

Bump Python to 3.10 and update deps to compatible versions.
This introduces pattern matching to Draconic (see avrae/draconic#13).
Fixes an issue where errors in f-strings in Draconic's tracebacks would point to the wrong line.

chore: bump python to 3.10

---

aliasing/api/character.py
aliasing/api/functions.py
aliasing/evaluators.py
cogs5e/models/character.py
docs/aliasing/api.rst

- The first `!update` from sheet v18 to v19 will no longer overwrite a coinpurse if it is not empty
- Moved `AliasCoinpurse.parse` to base function `parse_coins`
- Added `AliasCoinpurse.total`
- Added `autoconvert` arg to `AliasCoinpurse.modify_coins`

Changes from Coinpurse Feedback

---

cogs5e/sheets/gsheet.py

Change ``.value`` to ``.unformatted_value`` to account for localization

Gsheet Coinpurse Hotfix

---

cogs5e/lookup.py

Adds name hiding to monimage and monster lookup while still also respecting compact mode
Resolves #1350

Adds name hiding to monimage and monster lookup

---

cogs5e/lookup.py
cogs5e/models/embeds.py
gamedata/lookuputils.py
utils/constants.py
utils/help.py

This adds the name of the source to relevant search and select menus.
Additionally moves the homebrew icon/emoji to constants (and changes it to use the emoji from the Avrae Constants Guild)

Add sources to search and select lookup

---

cogs5e/initiative/cog.py

Enabling the ability to cast spells within a group in initiative

Adding Casting to Groups in Combat

---

aliasing/api/character.py

Add a cvar getter so that the entire dict of cvars does not need to be copied to get a specific cvar.

Add Cvar Getter

---

cogs5e/models/embeds.py
cogsmisc/tutorials/__init__.py
dbot.py
utils/config.py

Adds a /help slash command to explain the basics of prefix commands and direct users to using prefix commands.

feat: add help slash command

---

cogs5e/initiative/upenn_nlp.py

Adds a field to NLP recorded messages to determine whether or not the author was a bot.

chore(nlp): add author_bot field to recorded message events

---

cogs5e/lookup.py
cogsmisc/tutorials/__init__.py
dbot.py
gamedata/lookuputils.py
gamedata/shared.py

Adds slash commands to the various lookup commands. 
Ensures that entitlements are validated against and enforced on lookup, and works for homebrew as well.

Lookup Slash Commands

---

aliasing/api/character.py
tests/unit/aliasing/character_test.py

Add `AliasCustomCounter.mod(value, strict)`
Resolves #1862

feat(aliasing): AliasCustomCounter.mod 

---

aliasing/api/statblock.py
tests/unit/aliasing/statblock_test.py

Add `AliasBaseStats.get(stat)` and testing
Resolves #1861

feat(aliasing) AliasBaseStats.get

---

aliasing/api/character.py

fix: activation_type may be None

fix: activation_type may be None

---

cogs5e/models/dicecloud/autoparser.py
cogs5e/sheets/dicecloudv2.py

Deactivated spells (other than just unprepared spells) will no longer be added to spellbook
Slots is the sum of pact and normal slots, this I was unaware of
Attacks now display notes and description
Rounded proficiency to one decimal place so that it is importable.

Few more polishing touches for DCV2

---

cogs5e/models/dicecloud/autoparser.py

This regex should fix any remaining issues relating to the annostring parsing regex... I hope

fix(dcv2): regex is hard

---

cogs5e/lookup.py

Fixes `!condition`, `!monimage`, and adds a reference to slash command lookup to one of the tutorials.

Dec 7 Hotfix

---

cogs5e/models/dicecloud/autoparser.py
cogs5e/sheets/dicecloudv2.py

If activation type is non-standard, use special.
If an action errors because of a resource that is non-specific, mention it
Refactor parse_attribute into more manageable functions

DCv2: Refactor attribute parsing, and fix some errors

---

docs/aliasing/api.rst

Depends on PR avrae/draconic#20

docs: Add note for starred unpacking

---

aliasing/api/combat.py

Expose the ._hidden property for alias writing.

Add is_hidden to SimpleCombatant.

---

cogs5e/models/dicecloud/autoparser.py

Targets would append to stack instead of the root, as well as not persisting properly.

Fix Dicecloud V2 targeting problems

---

cogs5e/models/dicecloud/autoparser.py

Add a copy of the last node to the stack, instead of the target node itself.
Make DC not a required field for saves.

Targeting is hard

---

Dockerfile
Dockerfile.ci
cogs5e/charGen.py
cogs5e/gametrack.py
cogs5e/initiative/buttons.py
cogs5e/initiative/cog.py
cogs5e/models/automation/effects/check.py
cogs5e/models/automation/utils.py
cogs5e/sheetManager.py
cogs5e/sheets/dicecloudv2.py
cogs5e/utils/gameutils.py
cogsmisc/adminUtils.py
cogsmisc/customization.py
cogsmisc/tutorials/__init__.py
cogsmisc/tutorials/init_dm.py
cogsmisc/tutorials/runningthegame.py
cogsmisc/tutorials/spellcasting.py
tests/e2e/automation_effects_test.py
tests/e2e/cogs/customization_test.py
tests/e2e/cogs/dice_test.py
tests/e2e/cogs/initTracker_test.py
tests/requirements.txt
tests/unit/aliasing/evaluators_test.py
ui/charsettings.py
ui/servsettings.py
utils/constants.py
utils/enums.py

Updating Black to latest

---

cogs5e/sheets/dicecloudv2.py

Slot fillers were removed from DCv2, automatically replaced with folders, though the possibility of them being swapped for features is likely, so checking both.

Check folders and features instead of slot fillers

---

cogs5e/initiative/cog.py

Init note remove confirmation prompt

---

cogs5e/sheets/gsheet.py

This change makes it possible for gsheet to import half prof (rounded up) to basic stat checks str, dex, con from remarkable athlete. (A formula in cell AQ67 would have to be added first).

Added a Parser for Remarkable Talent for gsheet

---

.gitignore
cogs5e/gamelog/cog.py
cogsmisc/adminUtils.py
dbot.py
ddb/gamelog/client.py
docker-compose.yml
requirements.txt
utils/redisIO.py

Updating Redis

---

cogs5e/sheetManager.py
cogs5e/sheets/beyond.py

Allow `!import` to accept DDB PDF URLs, with a warning message.

Accept DDB PDF URLs with a warning

---

cogs5e/gamelog/cog.py

Adds a short summary about which campaign link to use.

fix(campaing): add desc for campaign link

---

cogs5e/gametrack.py
cogs5e/sheetManager.py
cogsmisc/customization.py
cogsmisc/tutorials/__init__.py

The [Inclusive Naming Initiative](https://inclusivenaming.org/word-lists/tier-1/abort/inclusive-naming-word-lists-v1.0.html) recommends replacing "abort" wherever possible.
The other tier-1 violation of avrae is the usage of "blacklist", but that is a function called by administrators, outside of this repository so I can't be sure renaming would be safe. Aborting only appears in strings, but they are user visible so arguably more important to remove

Inclusive naming/abort

---

cogs5e/sheets/dicecloudv2.py

Switches some direct indexes for invocations of `.get` instead, so that incorrectly formatted sheets can be imported but with missing content instead of failing entirely.
Also cleans up a stack of if statements that was getting a bit out of control.

Make Dicecloud V2 importer more lenient with missing keys

---

cogs5e/homebrew.py
cogs5e/models/homebrew/bestiary.py

This Pull Request does two things:
It adds support for bestiaries from https://bestiarybuilder.com/, a bestiary website designed for use with Avrae and convenience. 
It also fixes some very minor issues in the critterDB bestiary regex parsers to match current statblock formatting.
This pull request changes the bestiary schema to add a new field. I tested this change and I believe it is fine, but for my piece of mind I would appreciate if someone else also tested them.

Add support for Bestiary Builder bestiaries & Fix critterDB regexes

---

requirements.txt
utils/config.py

- [X ] This PR is not a code change (e.g. documentation, README, ...)

Feature upgrade packages

---

cogs5e/homebrew.py
cogs5e/models/homebrew/bestiary.py
dbot.py
scripts/ensure_indices.py
utils/config.py

Creating a split condition to repair complications with prior PR.  SSL/TLS will be disabled in Development Environment, and functional in others.

Updating Mongo Configuration for Environment Detection for Mongo SSL/TLS

---

dbot.py
requirements.txt
scripts/ensure_indices.py

Rolling back pymongo update to resolve TLS/SSL issues at a later date.

Rolling back PyMongo Version

---

dbot.py
requirements.txt
scripts/ensure_indices.py

Nightly Merge

---

cogs5e/initiative/cog.py
cogs5e/utils/targetutils.py
utils/functions.py

Adds some better cues for which item the search and select prompt is asking about.
Resolves #1863

feat(select): improve display

---

cogs5e/models/homebrew/bestiary.py
gamedata/monster.py

This fixes the import errors introduced in v4.3.2 when importing a bestiary from Bestiary Builder

Fix import errors

---

requirements.txt

Reverting Requirements.txt back to where it was prior to 4.3 release.

Reverting Requirements.

---

cogs5e/models/homebrew/bestiary.py
cogs5e/utils/checkutils.py

Weekly Merge from Nightly to Master

Nightly Merge to Master

---

dbot.py
requirements.txt

upgraded Disnake package to latest version and adding garbage collection method to address the memory leak which is being caused by the version upgrade 

Disnake version upgrade

---

gamedata/monster.py

Fixes that one error from critterDB

thanks critterdb

---

utils/img.py

Syncing Nightly with Master

---

cogs5e/models/homebrew/bestiary.py

This fixes daily spellcasting for BB

---

cogs5e/models/homebrew/bestiary.py
cogs5e/utils/checkutils.py

Syncing Master to Nightly

---

cogs5e/sheets/dicecloudv2.py

Undo all the `.get` I did on _by_type, since it's already a default dict and doing this just made things worse.
Unmake some of the mistakes to the DCv2 importer

fix(dcv2): oops I broke the importer

---

SECURITY.md
dbot.py
utils/img.py

Merging Nightly to Master

---

cogs5e/models/automation/runtime.py
cogs5e/utils/checkutils.py
tests/e2e/cogs/sheetManager_test.py

adds a block quote on all phrases in automation
Adds a blockquote on `-phrase`s for checks, saves, and automation.

 fix(automation): add difference between phrase and description 

---

requirements.txt
utils/img.py

Updating Pillow.
Updated Pillow to latest release providing added Security and Functionality

Upgrading Pillow back to 10.x

---

requirements.txt

Updating gSpread for security vulnerability fixes and code modernization.
gSpread updated from 3.7.8 to 6.0.0 and newer
- [] This PR fixes an issue.

AVR-387: Updating gSpread to 6.x

---

requirements.txt

We want to update all packages to newest versions for security purposes, as well as to be able to eventually update Python to a newer version.
rapidfuzz updated to 3.6.1 from 2.0.11

Updating Python Package RapidFuzz to latest version.

---

cogs5e/sheets/gsheet.py

It's safer to refresh the token before it expires rather than on the very moment it expires.
Fix token expiration issues

Fix token expiration related issues

---

cogs5e/utils/actionutils.py

Adds a (-1) when casting a spell with a spell slot.
Resolves #1999 (AFR-1019)
When casting a spell with a spell slot, a delta (-1) will now be shown.

Add Delta when casting a spell using a spell slot

---

aliasing/api/character.py

If `create_cc_nx` doesn't create a CC, it will return the CC that already exists.

fix(character): return existing cc in create_cc_nx

---

cogs5e/models/character.py
cogs5e/sheetManager.py
tests/utils.py
utils/context.py

This PR is to address the feedback received on the `!char channel` command.
1. Remove documentation from !char command embed
2. Change !char channel and !char server to toggle again
3. Fix !char embed to properly display if a character is global or server and not have the fallback happen

Addressing most of the common feedback for '!char channel' command

---

cogs5e/models/character.py
cogs5e/sheetManager.py

Remove any prompts for char server, channel and resetall commands
Remove any prompts for char server, channel and resetall commands

Remove prompts for all char channel/server commands

---

cogs5e/sheetManager.py

1. Ensure char channel is working correctly
2. All toggling of characters is working correctly
3. Messages are cleaned up

Address more char channel and char server feedback to clean up inconsistencies and fix bugs

---

cogs5e/sheetManager.py

Fix an error 'Error: Command raised an exception: UnboundLocalError: local variable 'channel_character' referenced before assignment'
Add a none declaration for a variable

Add a none declaration for both channel and global_character

---

cogs5e/sheetManager.py

Fix resetall missing a parameter

Pass None into unset_active_channel_helper for resetall

---

cogs5e/models/character.py

Add previous character parameter to pass into helper

---

cogs5e/sheetManager.py

Address top feedback on !char embeds

Switch to disappearing messages for embed

---

cogs5e/sheets/beyond.py

In working to update the character computational endpoint from DDB -> Avrae, we have built it directly into the SCDS Rest API to have native support going forward with any changes to Rules/Games Engine from DDB's side to translate smoothly into Avrae.

Updating to utilize new REST Endpoint for Avrae Character Computations directly from SCDS

---

cogs5e/sheets/beyond.py

Currently, you had to have a public sheet, and had to get the shareable link or PDF to import character.  Now, you can copy the direct link to the character sheet from your browser.

Resolve direct Character URLS

---

cogs5e/models/character.py
cogs5e/sheetManager.py
cogs5e/sheets/beyond.py

Adding more options to unset context.
1. Add a !char global <name> command
2. Add a reset/unset parameter to !char server and !char channel
3. Improve documentation

Add !char global command and reset parameter to server and channel commands

---

cogs5e/models/character.py

A method was marked as async but didn't need to be

Remove unnecessary async decoration on method

---

cogs5e/models/character.py
cogs5e/sheetManager.py

Switch to using subcommands for reset on server and channel

Switch to using subcommands for reset on server and channel

---

cogs5e/sheetManager.py

Clean up documentation and remove toggle for server and channel commands

Clean up documentation and remove toggle for server and channel commands

---

cogs5e/sheetManager.py

Makes `!save death` a subcommand to make it less of an oddity to maintain
Make `!save death` a subcommand

make !save death a subcommand

---

cogs5e/sheetManager.py

Added a newline for summary docstring in `!help` as well as more concise command specific help description.
Existing docstring was too long for `!help` display without a newline and a bit confusing.
Added a newline for summary docstring in `!help` as well as more concise command specific help description.

Update `!character` docstring

---

cogs5e/gamelog/utils.py

We are seeing some activity in logs with some crashes due to this LaunchDarkly request.

Swapping gamelog featureflag to new LD SDK

---

.gitignore
dbot.py
utils/functions.py

Updates un Fuzzy search to improve results and prevent showing false positives.
- [x ] This PR fixes an issue.

Avr 409 fuzzy update

---

dbot.py
requirements.txt

AWS is deprecating some Mongo Instances, so we are going to attempt to tackle Instance type and Version in one push.
Update Mongo Libraries, and Engine

Updating Mongo 

---

docs/automation_ref.rst

This should be marked as optional.

Mark attribute as optional

---

utils/dice.py

rstrip backslashes from `!roll` VerboseMDStringifier

Update dice.py for AVR-944

---

cogs5e/models/automation/runtime.py
utils/dice.py

Fixes an issue where combatants without HP would cause a break in code with the HP Deltas.
Bug Fix for HP Delta

Fixing HP Delta for odd usecase

---

cogs5e/lookup.py

Added /lookup commands for "species" and "speciesfeat"

Slash commands for species and speciesfeat

---

cogsmisc/adminUtils.py

"register_commands" Admin command.

Admin register slash command

---

cogsmisc/adminUtils.py
dbot.py

Upgrading the Command Sync functionality to fit the current method used by Disnake
Fixed Slash command Sync

Updating Command Sync Functionality

---

cogs5e/lookup.py
cogs5e/sheetManager.py
gamedata/lookuputils.py

Code cleanup. Removed testing functions.

Code cleanup

---

dbot.py
ddb/gamelog/client.py

Redis Health Checks

---

gamedata/lookuputils.py

A few more fixes came up to be fixed.  Working them here.

A few more Spellbook Fixes

---

cogs5e/sheets/beyond.py

Let's stop duplicates from DDB, Shall we ?

Additional Spellbook Fixes

---

cogs5e/lookup.py
cogs5e/sheetManager.py
cogs5e/sheets/beyond.py
gamedata/lookuputils.py
ui/servsettings.py
utils/settings/guild.py

Adding a version field to server settings. The version can be switched via the !servsettings command > Miscellaneous Settings

Servsetting version added for server settings

---

ddb/gamelog/client.py

Adding a try catch around the loop of listen to fix it.  Thanks to @devgr  for the help!

Possibly fix the Gamelog Disconnects

---

.github/workflows/deploy.yml
cogs5e/sheetManager.py
gamedata/lookuputils.py
ui/charsettings.py
ui/servsettings.py

Updating some items found in release for a Hotfix

---

ui/servsettings.py
utils/settings/guild.py

- Add a flag in servsettings for "Allow character override"
- Add a UI button to toggle the new flag/setting

Added UI button for character override

---

cogs5e/sheetManager.py

Fixes the import error when importing a character in DMs without adding a version.

Fix import error in DMs

---

utils/functions.py

Adds channel mention to monster selection dialogue
Added a mention to the channel in which the response to the monster selection dialogue will be sought.

Adds channel mention to monster selection dialogue

---

requirements.txt

hotfix: boto3 added

---

gamedata/lookuputils.py

Check if command is coming from DM or server and apply logic for character overrides if done in DMs
Default to character settings if lookup done in DM

Lookup fix to account for character version in DMS

---

gamedata/lookuputils.py

Updated if checks

---

utils/datadog.py

dd.env variable defined in the custom logger was conflicting with the env variable defined in the ecs logConfiguration

AVR-572 removing conflicting environment variable in datadog logger

---

cogs5e/lookup.py

Fix for lookup race and lookup spell

Lookup command fix

---

cogs5e/lookup.py
gamedata/lookuputils.py

Resolves #2098 
account for interaction context vs avrae context in version lookup

fix: enhance server settings retrieval and character version handling

---

cogsmisc/adminUtils.py

Add Embed Pagination to Ping-all for cluster ping tests
Add admin refreshteam
not needed, admin only

Update admin commands

---

requirements.txt
utils/datadog.py

Updating Datadog and changing sampling rate from 90% to 10%
Updated Datadog

Datadog Tweaks

---

cogs5e/lookup.py
gamedata/lookuputils.py

Update `get_version_lookup` to better handle DM queries and hierarchy. 

refactor get_lookup_version to improve server settings handling

---

requirements.txt

Update autommation-commons version

Update autommation commons version

---

cogs5e/gametrack.py

allow "" version

---

cogs5e/dice/cog.py
cogs5e/gametrack.py
cogs5e/initiative/cog.py
cogs5e/lookup.py
gamedata/compendium.py
gamedata/lookuputils.py
gamedata/spell.py

Fix version checking for spells. New "version" for `Homebrew`
Fix version checking for spells and added lookup hierarchy.
Prioritize homebrew and versioned spells. Non-versioned spells will be valid if a a versioned alternative is not found.

Spell Casting/lookup fixes

---

cogs5e/lookup.py
docs/automation_ref.rst
gamedata/lookuputils.py

Normalize version string matching and fix an issue where the slash command for rule was showing  a homebrew option

Enhance version extraction and filtering logic for spells and rules

---

cogs5e/sheets/beyond.py

third time's the charm?
Prepared spells should always be prepared even with the same spell unprepared in another class (looking at you clerics)

Update beyond.py for prepared spells

---

cogs5e/sheetManager.py

Handle the case where the user is running the command in DM's. This would error out if the user tried to import a 2014 sheet via dm. 

Alow `!import` to be ran in DM's with a version parameter

---

cogs5e/sheetManager.py
gamedata/lookuputils.py

Resolves #AVR-1043
Enhance slash_match_key to include legacy status and fix item converter type

Enhance slash_match_key to include legacy status and fix item converter type

---

cogs5e/initiative/combatant.py
cogs5e/models/sheet/attack.py

prevent invisible error w/ list display override on generic combatant
Fixed adding actions to generic combatants with action display overrides.

fix(combat): prevent invisible error w/ list display override on generic combatant

---

.gitignore
README-docker.md
confluent_client/producer.py
dbot.py
docker-compose.kafka-dev.yml
utils/config.py

Re-introduces Kafka integration with improved analytics and event logging, along with updates to the development environment setup to support Kafka. The main changes include enhancements to the Kafka producer implementation, new event listeners for analytics, updates to the development configuration files, and feature flags around producer calls.
Re-implement command analytics with improved Kafka producer and feature flags

feat(AVR-1002): improve kafka producer configuration and logic

---

docs/automation_ref.rst

Added SRD monster action reference to automation docs.
Added SRD monster action reference to automation docs.

docs(automation): include SRD actions reference in docs

---

README-docker.md
README.md

The instructions for creating a Discord bot user are no longer accurate, this PR fixes that.

docs: update Discord bot creation instructions for clarity and detail

---

cogs5e/models/automation/__init__.py
cogs5e/models/automation/effects/castspell.py
cogs5e/utils/actionutils.py

fix to actually show spell range
n/a

fix: fix spell range behavior
