avrae/avrae

cogs5e/sheetManager.py
cogsmisc/customization.py

Commands should default to list. I think I saw a feature request or something somewhere. Just used the same format as alias and snippet.
Also using GitHub to make changes is the worst. Can't figure out how to squash them locally. RIP

Added default commands to cvar, gvar, uvar

---

cogsmisc/customization.py

Using loops you can get multiline to run for a very long time.
Limiting it to 100 helps fix potential spam abuse.
Maybe lower the number to about 40-60 instead. (Meaning avrae will only run commands for a full minute or so and will stop after that)

Limit multiline to defined number of commands

---

cogs5e/initTracker.py

Simply .lower() the input of args for `-resist` `-immune` and `-vuln`
So that 
Bludgeoning == bludgeoning == BluDgeoNing
Biggest issue I see is any potential resists that exist before this that have capitals can't be removed? I wasn't sure how to fix that, other than something like
combatant.resists['resist'] = list(set(i.lower() for i in combatant.resists['resist']))
But I figured you wouldn't want that running every time opt? I dunno

Allow resist args for `!i opt` be case insensitive

---

cogs5e/initTracker.py

Fixes #87 
`-criton` still overrides the csetting

Make csetting `criton` work in init

---

cogsmisc/customization.py

I dunno if this change breaks any intended fail safes.
Since multiline is processed in bulk on the backend, allowing the commands in multiline to use ! as opposed to
the guild prefix shouldn't cause any issues with other bots.
Trying to think of what the intent was behind killing the multiline command if it used the default prefix?

Multiline Change for Alternate Prefix Servers

---

cogs5e/models/monster.py

Resolves #625
Moved location of monster images to `media.avrae.io/:src/:monster`.

[WEB-026] Update monster media URL

---

cogs5e/dice.py
cogs5e/gametrack.py
cogs5e/initTracker.py
cogs5e/models/character.py
cogs5e/models/homebrew/bestiary.py
utils/functions.py

Fixes:
- AVR-321 #615 - This is done by running `fuzz.partial_match` on `key(first_result)` and `query` - if they are less than 75% similar, it'll open a dialog instead of assuming the only match is correct
Example: `!feat` only returns Grappler, the only SRD feat
- `!feat crossbow expert` opens dialog
- `!feat grap` returns Grappler
- `!feat gpler` returns Grappler
- `!feat gour` opens dialog
- AVR-324 #627 
Other changes:
- Removed some old search methods
- Moved some functions over to using `search_and_select` instead of manually building select list and using `get_selection` (namely, monster attack and init attack)

Bugfixes: 2019w25

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/internal-enhancement.md

These templates should automatically label new issues with the right labels for Taine. If accepted, will also add these templates to avrae/avrae.io, avrae/avrae-service, and avrae/taine.

Add issue templates

---

README.md
cogs5e/sheets/gsheet.py
docker/readme.md

Uses an env var to authenticate with Google Spreadsheets instead of a JSON file. Falls back to JSON if the env var is not found.

Use env var to auth with Google

---

cogs5e/gametrack.py
cogs5e/initTracker.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/spell.py
cogs5e/sheets/beyond.py
cogs5e/sheets/gsheet.py

Resolves #592 
Resolves #655 - If a caster attempts to cast a spell whose default level is a level they have no max slots for, automatically upscale to the next lowest level they have slots for, below level 5 (for warlocks)
Resolves #669 
**Old DDB Import Bugs**
Resolves #585 
Resolves #664 
Resolves #670 
Resolves #628 
Resolves #679 
Resolves #671 
Resolves #683 
Resolves #642

Fixes: 2019w28

---

cogs5e/funcs/lookupFuncs.py
cogs5e/homebrew.py
cogs5e/models/errors.py
cogs5e/models/homebrew/bestiary.py
cogs5e/models/monster.py
migrators/bestiary_hasher.py
notes/dbIndices.txt

Resolves #676 
The largest source of duplicate data in bestiaries is multiple users who have imported the same bestiary - the old system would store a copy for each user, leading to a lot of identical data. Since bestiaries are read-only, this change implements a hashing system to track identical bestiaries. If two users import an identical bestiary, it will now mark two "subscribers" on the same hashed bestiary, removing duplicate entries.
Running a test on a local copy of the database, this reduces the space needed to store bestiaries by 79.7% (as of 44ab986).
- N/A I have updated the documentation to reflect the changes.

[GH-676] Better Bestiary Storage

---

cogs5e/sheets/beyond.py

Fixes AVR-359 (#706) where sheets error on import due to houserules not having a value
This has generally occurred when they have a note but without a value, which led to them being in the list of values to apply with a NoneType as their value, causing an error on import
(Note: As far as I could tell this does not occur when houseruling proficiency type, only bonuses.)
This PR fixes the issue by adding Try/Except blocks to the relevant sections where it can error.

AVR-359 Fix import error of houserules w/o values

---

requirements.txt

Bumps tensorflow to 1.14 and changes pygsheets to use the main fork now that it's fixed.

Bump tensorflow to 1.14, use main pygsheets fork

---

cogs5e/funcs/scripting/combat.py
cogs5e/models/initiative.py
tests/utiltests/argparser_test.py
utils/argparser.py

Fixes a major issue breaking aliases in Chromatic Blue (caused by https://github.com/avrae/avrae/commit/30566c67c19cac8a96a489091eab20ff48d9295d)
Resolves #756 
Resolves #755 
- Semi-reverts a breaking change.

Hotfix: Some issues from v1.1.0

---

cogs5e/dice.py

Added the missing underscore for the help text of roll on line 53.
Added the missing underscore for the help text of roll on line 53.

Fix AVR-413

---

cogs5e/funcs/dice.py
tests/dice_roller_test.py

Limits rolls to a total of 1000 dice rerolls. It should be highly unlikely for any normal roll to hit this.

add stricter reroll limit

---

docs/aliasing/api.rst
docs/automation.rst
docs/index.rst

Moves automation system documentation to readthedocs from avrae/avrae-spells.

add spell automation docs

---

cogs5e/initTracker.py

Allow for `!init opt` to modify values using + or -, adding the ability to make modifications on the fly without having to provide a hard value. Also adds delta's to those values.
Affects: `-p`, `-ac`, `-max`, and `-hp`

Allow for `!init opt` to modify values using + or -

---

cogs5e/initTracker.py

Fixes `-custom` attacks in initiative by creating an automation object. 
The old implementation was returning:
```py
Error: Command raised an exception: AttributeError: 'dict' object has no attribute 'name'
```

Fix `-custom` attacks w/ automation

---

cogs5e/initTracker.py

Adds a `-parent` argument for `!init effect`, allowing a parent effect to be set outside of scripting.
Also adds group targeting for the first target of `!init effect` and for `!init re`.

Adds a `-parent` argument for `!init effect`

---

cogs5e/dice.py
cogs5e/funcs/attackutils.py
cogs5e/initTracker.py
cogs5e/models/monster.py
cogs5e/models/sheet/attack.py
cogs5e/sheetManager.py
migrators/combine_monster_automation.py

This PR adds the framework for the full automation of monster actions. Most notably, it adds `proper` and `verb` attributes to Attacks and changes `SheetManager.attack`, `Dice.monster_attack`, and `Initiative._attack` to all use `attackutils.run_attack()`.
This change should not be breaking to any of the changed models (there are no proper nouns in the SRD monsters, either).

Monster automation framework

---

cogs5e/homebrew.py

`!help bestiary import` has been missing a ` for some time now. This puts it back in.

Fix missing ` in help

---

cogs5e/gametrack.py
cogs5e/lookup.py
cogs5e/models/automation.py
cogs5e/models/embeds.py
cogs5e/models/spell.py
cogs5e/pbpUtils.py
tests/cogs5e/dice_test.py
utils/functions.py

In the latest Discord update, the layout of inline fields in embeds was changed to force inline fields into a column instead of allowing them to dynamically choose a size. This PR explicitly sets some fields to be non-inline.
Additionally, this adds the ability for `!embed` to add inline fields, with `-f title|desc|inline`.

Embed Formatting Changes

---

cogsmisc/customization.py
tests/mixed/aliasing_mixed_test.py

Modifies the output of the `!snippet`, `!servsnippet`, `!alias`, and `!servalias` commands when displaying snippets/aliases, both on creation and during look up. This keeps everything consistent, and within proper code blocks, hopefully reducing the amount of miss-copied aliases/snippets.

Modify snippet/alias display

---

cogs5e/sheets/beyond.py

This PR fixes the warforged AC calculation. I did not see an open issue for this but if necessary I can make one.
This is the official Warforged description for AC calculation
This is the generated character sheet from dndbeyond:
Here is the character that is imported into avrae showing the extra proficiency bonus (+2) being erroneously added to the character's AC

fix warforged ac value

---

cogs5e/sheets/dicecloud.py

Resolves #989 
Adding the dicecloud function "larger(x, y)" to the dicecloud parser. 
I have not tested the code, as I wrote the PR on the train and I'm close to where I exit. If anyone that has the testing environment setup, code can be tested by running:
!dicecloud https://dicecloud.com/character/mWSQosLimL37cmiCK/AvraeTestChar
Thanks!

Add larger(x,y) to dicecloud integration

---

cogs5e/sheets/beyond.py

Automatically add the `ro<3` for the Great Weapon Fighting fighting style to two handed melee weapons.

Add Great Weapon Fighting Support

---

dbot.py
utils/clustering.py

Strengthens the lock during initial bot startup to avoid hitting the 1 IDENTIFY/5s ratelimit from Discord multiple times when restarting multiple clusters.

2020w14 - lock improvement

---

cogs5e/sheets/beyond.py

Checks if the player is an Artificer with the Battle Ready feature, and if so, uses int for their magic weapons mod bonus

Add support for Battle Master Artificer's Battle Ready feature

---

README.md

The Python requirement stated in the readme for hosting a local copy of Avrae did not match with the actual requirement (namely, >= 3.8.0 as opposed to >= 3.6.0 < 3.7)

Update stated Python requirement to '>= 3.8.0'

---

cogs5e/sheetManager.py

`!update` made reference to the removed argument `-cc` and did not mention the new `-nocc` present in `!beyond` and `!dicecloud`'s documentation. This fixes that.
Fixes #1143

Fix docstring for `!update` to include `-nocc`

---

cogs5e/gametrack.py
tests/cogs5e/gametrack_test.py

Small PR that adds death save details to `!g status`. Will only show saves when they are not zero.
Resolves #1237 (AFR-620)

Added Death Saves to game status as well as append test for it

---

cogs5e/models/sheet/attack.py

Moves attack list sorting from `str` to class initialization. This fixes the issue of attacks being in different spots in the data vs the str.

Move Attack sort from str to initalization

---

aliasing/api/combat.py
aliasing/api/context.py
aliasing/api/statblock.py
aliasing/evaluators.py
cogs5e/lookup.py
docs/aliasing/api.rst

Cleans up some bugs in the nightly release of the workshop.
- fixes `AliasSkill.d20()` defaulting to dis
- fixes some documentation saying the wrong things
- fixes running aliases in PMs
- fixes issue where selection menus would be broken

various workshop bugfixes

---

cogs5e/initTracker.py

Previously `!i status` required a name, now it will default to the current combatant.
Resolves #1236 (AFR-619)

Set init status to default to current combatant

---

cogs5e/initTracker.py

Adds `-note <note>` as an argument to `!init add` and `!init madd`
Resolves #1211 (AFR-603)

Allow adding combatants with starting note

---

cogs5e/lookup.py
cogs5e/sheetManager.py
gamedata/monster.py
tests/static/compendium/srd-bestiary.json
utils/config.py
utils/constants.py
utils/img.py

Depends on avrae/avrae-terraform#58
Adds code to display monster tokens.
- Resolves #1217 
- splits `!token` and `!monimage` to get monster tokens and images, respectively
- monster tokens are cached until bot restart per cluster
- refactored `img.generate_token` to handle border selection
*When releasing, set `DO_RELEASE=0` in travis, let TF do the release!*

Monster Token Project

---

cogs5e/initTracker.py

Fixes specifying only `-p` with `!init add` still rolling for init.
Closes #1250 (AVR-644)

Fix AVR-644

---

aliasing/evaluators.py
docs/aliasing/api.rst

Adds `enumerate` to the aliasing context
Not 100% sure if I did the docs right.
Resolves #1185 (AFR-590)

Add Built-In Enumerate to Aliasing Context

---

aliasing/api/combat.py
cogs5e/initTracker.py
cogs5e/models/automation.py
cogs5e/models/initiative.py

This adds a `-desc` argument to `!init effect`, as well as to automation and `SimpleCombatant.add_effect()`.
I still need to add this to the actual Automation editor for spells and attacks, but I confirmed it works with `!attack import` using a modified JSON to add the `desc` tag to an ieffect.
Resolves #890 (AFR-465)

Add descriptions to Init Effects

---

cogs5e/initTracker.py
cogs5e/models/initiative.py

Adds an option to not remove `MonsterCombatant`s when they are below 0 hp
Fixes bug where removing a monster as the last combatant would error.
Resolves #1194 (AFR-595)
Fixes #1286 (AVR-658)

Add an option to not remove monsters at below 0 hp

---

aliasing/api/context.py

Exposes the name the alias was invoked with under `ctx.invoked_with`
Resolves #1294 (AFR-650)

Expose alias invocation name

---

aliasing/api/functions.py

The current docs link `SimpleRollResult` to `cogs5e.functions.scripting.functions.SimpleRollResult` on `vroll`, but the current `SimpleRollResult` class is under `aliasing.api.functions`.

Change Class of SimpleRollResult in Vroll docs

---

cogs5e/dice.py
cogs5e/initTracker.py
cogs5e/models/automation.py
cogs5e/sheetManager.py

Summary
========
Adds the `-nocrit` argument for attack spells and attacks (notably the Target and Damage automation effects)
Issues
-------
Resolves #1216 (AFR-606)

Add nocrit arg to nullify critical attacks.

---

aliasing/api/combat.py
cogs5e/models/initiative.py
docs/aliasing/api.rst

Summary
========
Expose list of groups to `SimpleCombat`. Also makes the group's name available.
Additions
---------
**For Aliasing**:
`SimpleCombat.groups` - List of `SimpleGroups` in a combat
`SimpleGroup.name` - Name of the group
**Background Methods**
`Combat.get_groups()` - Returns a list of `CombatantGroups`
Issues
-------
Resolves #1284 (AFR-642)

Expose list of groups to SimpleCombat

---

aliasing/api/context.py
docs/aliasing/api.rst

Adds a property to AliasContext to represent the category of the channel that it has been executed in.
Resolves #1333 
`AliasChannel` -
* `AliasChannel.category`
`AliasCategory` -
* `AliasCategory.name`
* `AliasCategory.id`

Add channel category to AliasContext

---

cogs5e/models/sheet/player.py

Resolves #1345
CC creation now allows not providing `max` when providing either `resetto` or `resetby`

Adds handling for resetto or resetby when no max

---

aliasing/api/character.py

Summary
========
Adds the ability to get the `AliasConsumable` from a name. I implemented it as a non-breaking change, but I am interested to see what people think about making it a breaking change by replacing `AliasCharacter.get_cc`
Additions
---------
`AliasCharacter.cc(name: str)` - Returns the `AliasConsumable` from the name.
Issues
-------
Resolves #1339 (AFR-671)

Adds get_consumable to AliasCharacter

---

cogs5e/models/automation.py
docs/aliasing/api.rst
docs/automation_ref.rst

Resolves #1335 
Closes #1332
This PR expands on the use of variables in the Automation engine to accomplish things that were previously impossible (such as spells that did different amounts of damage based on the target's health, spells that healed the caster for the amount dealt only on a hit, and spells that otherwise required certain types of state tracking).
Examples of how to accomplish these can be found in `docs/automation_ref.rst+L499`.
- added Set Variable effect
- added Condition effect
- most effects now bind some variables based on their results
- avrae-service and avrae.io PRs to add support for these effects on the site
- update existing spells/monsters to utilize (e.g. Toll the Dead, Vampiric Touch)

AFR-670: Add more expansive variable support in Automation

---

cogs5e/gametrack.py

Summary
======
Adds a delta `(+/-x)` when changing spell slots with `!game spellslot` (`!g ss`)
Resolves #1374 (AFR-695)
Checklist
=====

Add Spell Slot Delta

---

tests/utiltests/argparser_test.py
utils/argparser.py

Summary
======
Adds the `custom` kwarg to `ParsedArgument.adv` which allows for the user to override what the function looks for.
Example dict of a custom argument:
```py
{
'adv': 'custom_adv',
'dis': 'custom_dis',
'ea': 'custom_ea'
}
```
The current implementation will only pull items from the dictionary that exist, so you can have a custom adv without a custom dis and vice versa.
Note: I realize the doc string is extremely long but I couldn't get it to be <120 characters per line without a line break. I tested it a 
few times with the built docs but I think this way looks the best with what I know.
Issues
------
Resolves #1359 (AFR-686)
Checklist
=====

Add custom advantage parsing

---

aliasing/api/functions.py
aliasing/helpers.py

Summary
======
Adds an argument in aliasing to `err` to allow for the alias not to PM the user.
Issues
------
Resolves #1357 (AFR-684)

Change default behavior on err to not PM the user

---

aliasing/api/combat.py
cogs5e/initTracker.py
cogs5e/models/initiative.py

Summary
======
Allows aliases to set the group of a combatant.
Adds `Combatant.set_group(group_name: str)`
Changes `!i opt` to use the new method on Combatant
Adds `SimpleCombatant.set_group(group: str)` which uses `Combatant.set_group`
Issues
------
Resolves #1317 
Checklist
=====

Allow aliases to set combatant groups

---

dbot.py
utils/clustering.py
utils/redisIO.py

Adds support for launching multiple shards concurrently (see https://discord.com/developers/docs/topics/gateway#session-start-limit-object). Note that `max_concurrency` actually refers to the number of concurrent IDENTIFY buckets, calculated by `shard_id % max_concurrency`.
The strategy here is to lock each of these buckets for 5 seconds in Redis each time a shard launches.

Large Bot Sharding: Concurrent Startup

---

aliasing/evaluators.py
docs/aliasing/api.rst

Summary
======
Adds the built-in python function `abs` to the Draconic evaluator in Avrae.
Resolves #1466 (AFR-760)
Checklist
======
PR Type
--------
Other
--------

Add `abs` to draconic evaluator

---

cogs5e/initTracker.py
cogs5e/models/automation/effects.py
cogs5e/models/initiative/effect.py

Summary
======
Adds an argument to `!init effect` (`magical`) that changes all damage to magical.
Resolves #1063 (AFR-540)
Checklist
======
PR Type
--------
Other
-------

Add magical arg to effects

---

cogs5e/models/automation/effects.py

This implements AFR-790, allowing the `-critdice` argument in attacks to overwrite the critdice csettings.

Allow for `-critdice` to overwite the csetting

---

cogs5e/sheetManager.py

Makes character portraits hidden when `-h` is passed for `!attack`, `!check`, and `!save`
Resolves #1351 (AFR-677)

Hide character portraits when -h is passed

---

cogs5e/models/sheet/player.py

This should not allow the creation of empty names for counters which breaks the `!cc` command later on since the field name can't be empty.
See https://discord.com/channels/269275778867396608/795768989729030165/849614250750115861 for context.
I think only the tab, space, and empty character are needed for this check since it seems those are the only ones causing an error later on. I'm not sure if there are any other characters that should be included.

Catching empty names for cc's

---

cogsmisc/customization.py

Adds Discord Slash-command conflict checking to prevent Avrae from becoming non-responsive to a prefix.

Add slash command check

---

cogsmisc/tutorials/init_dm.py

Added that you can input a dice string when determining monster count in the DM Initiative Tutorial.

DM Initiative Tutorial - Dice String

---

cogs5e/models/automation/effects/attack.py
cogs5e/models/automation/effects/damage.py
cogs5e/models/automation/effects/save.py
cogs5e/models/automation/runtime.py

~~Adds handling for nocritical that pairs with underlying nocrit.~~
Ignores crit state for children of Save automation, restoring it afterwards. Allowing a damage's dice to not be doubled on critical. Mostly intended for saves as part of attacks. (Snake poison, etc)

Ignore crit state on children of Save Automation

---

cogs5e/initTracker.py
cogs5e/models/automation/effects/attack.py
cogs5e/models/automation/effects/save.py
cogs5e/models/initiative/effect.py
cogs5e/utils/checkutils.py
utils/argparser.py
utils/functions.py

Resolves #432
Adds `adv/dis` and `sadv/sdis <ability>` to `!i effect`. Both only activate if no other advantage args were passed in before the effects are resolved.

Adds (s)adv/(s)dis to effect

---

cogs5e/gamelog.py
cogs5e/gametrack.py
cogs5e/sheetManager.py
cogsmisc/adminUtils.py
cogsmisc/customization.py
cogsmisc/tutorials/__init__.py
cogsmisc/tutorials/init_dm.py
tests/cogsmisc/customization_test.py

Updates all instances of confirm() without custom reply to use the default reply text `(Reply with yes/no)`
Updates snippet/alias test to match new format

Unify reply text, update test

---

aliasing/api/combat.py
cogs5e/models/initiative/combat.py
cogs5e/models/initiative/combatant.py

SimpleCombatant.group is returning Id instead of Name. Now returns the name or none as per spec.

Return group.name instead of group_id

---

aliasing/api/character.py
cogs5e/gametrack.py

Resolves #AFR-746
Add Simple Pagination to Custom Counters. Now doesn't prevent seeing past the 25th counter.
Adds `full_str()` accessibility to AliasCounter
Sometimes you have to do something dumb, before you can smart.
Special thanks to Derixyleth
Release Note: Adds Paging for Custom Counters, no longer preventing you from seeing past the 25th counter. Also adds a full_str() command to AliasCounter for showing the complete counter info.

Add Simple Pagination to Custom Counters

---

aliasing/api/character.py

The `\n` in the code ouput on the documentation is mangling for AliasCounter.full_str
This displays correctly, uncertain if is correct output though

Display is mangled for AliasCounter.full_str

---

aliasing/api/character.py

Fixes the other issues with full_str example display: does not take the counter name in context

full_str does not take the counter name in context

---

aliasing/api/combat.py

Adds methods to allow aliasers to access a combatant's id, and get a combatant by their id.
Resolves #1615 
+ Added `SimpleCombatant.id`
+ Added `SimpleGroup.id`
+ Changed `SimpleCombat.get_combatant` to document get combatants or groups by ID

Grant access to combatant id

---

aliasing/api/combat.py
docs/aliasing/api.rst

Aliases can currently read and set the initiative of SimpleCombatants, but there is no functionality to set the same for SimpleGroups. This PR aims to add feature parity by adding an `init` getter and setter to the API.

Add methods to manage Group initiative

---

aliasing/api/combat.py
cogs5e/models/initiative/combat.py

This change allows alias users to reset the current round and move initiative to its initial state, allowing plug-ins for the `!init reroll -restart True` command that handle initiative differently.

Allow manipulating the current round through automation

---

aliasing/api/combat.py
cogs5e/models/initiative/combat.py

Adds the ability to specify the strictness of matching for `get_combatant` and `get_group`.
None  - strict and then partial match
False - only partial match
True  - only strict match

Adds ability to set strict setting for combatant/group matching

---

cogs5e/gametrack.py
cogs5e/models/character.py
cogs5e/models/sheet/spellcasting.py
cogs5e/sheets/beyond.py
cogsmisc/tutorials/spellcasting.py
gamedata/spell.py
utils/constants.py
utils/functions.py

- Updates the hint in the Spellcasting tutorial to show even if the caster is not a full Warlock
- Displays pact slots differently from non-pact slots
- Refactors the character used for bubble display to a constant
- Fixes an issue where DDB import would fail if the user had no account linked
- Fixes ghost slots appearing on the first update that grants pact slots

Pact/Prepared Improvements

---

aliasing/evaluators.py
tests/aliasing/evaluators_test.py

Added the `sort_keys=False` kwarg in the `yaml.dump` method to prevent the ordering of the yaml string to break.

Do not sort keys

---

cogs5e/dice.py

`!roll` help mentions Great Weapon Master (the feat) instead of Great Weapon Fighting (the fighting style)

Fixed typo in `!roll` help string

---

cogs5e/initTracker.py
cogs5e/lookup.py
cogsmisc/tutorials/__init__.py
ui/charsettings.py
ui/servsettings.py
utils/settings/guild.py

- Adds the ability for server admins to select which roles count as a DM for monster lookups and init management
- Fixes an issue where !monster would error in PMs
Merging into nightly

Nightly: Settings Menu DM Roles

---

cogs5e/dice.py
cogs5e/lookup.py
tests/cogs5e/dice_test.py
tests/conftest.py
tests/utils.py
ui/charsettings.py
ui/menu.py

- Fixes an issue where certain RollErrors (e.g. divide by zero) would not output an error in inline rolling
- Improves the csettings color selector behaviour on an invalid color
- Only displays csettings pact slots note if character actually has pact slots
- Fixes an issue where the last context in an inline roll would not trim if it was over 128 characters
- Fixes an issue where the csettings color selector would not work in DMs
- Fixes an issue where `!monster` would not work in DMs
- Added the ability to choose DM roles through the servsettings menu

Settings Menu Fixes / DM Role Select

---

cogs5e/sheetManager.py

Makes it so `!char <name>` deletes the message after 15s (30s if active server character is unset)
This does not affect `!char server` messages.

feat(sheetManager): add deleteAfter to character switch

---

cogs5e/homebrew.py
cogs5e/models/homebrew/bestiary.py

Allows Avrae to parse YAMLs within `<avrae hidden></avrae>` tags in CritterDB action descriptions. Old override patterns still work too.
It appears to work but I am new to this so would appreciate more experienced people checking/improving the code.
I prepared a test monster with one attack that isn't overridden, one that's overridden using the old format, one that's overridden with a JSON and one that's overridden with a YAML.
https://critterdb.com/#/publishedbestiary/view/61ab7827e6e6ad7f5718c354
FR got 16 upvotes but I don't think it's still open. https://discord.com/channels/269275778867396608/834514549356625960/834970483148587048

Parse automation YAMLs in CritterDB descriptions

---

cogs5e/sheetManager.py
ui/servsettings.py
utils/settings/guild.py

Added a new server setting to check to toggle the campaign CTA that appears when you import or update a character, as well as making the necessary checks in send_ddb_ctas()
Changes to be committed:
modified:   cogs5e/sheetManager.py
modified:   ui/servsettings.py
modified:   utils/settings/guild.py

Add the option to disable campaign CTA in server settings

---

gamedata/monster.py

This change resets a monster's daily spells when `.reset_slots()` is called.

Reset monster daily spells like leveled slots

---

cogs5e/models/homebrew/bestiary.py

Thanks to Croebh, you too can shamelessly get +1 commit on the graph.
With the regex as it stands, it would only catch slot descriptions that are plural, such as "2 slots" or "3 slots", but it would ignore the singular form "1 slot". This fixes it by making the trailing `s` optional.

Fix bestiary spellcasting not catching "1 slot"

---

cogs5e/models/automation/effects/attack.py
cogs5e/utils/help_constants.py

Add Forced Rolls as an ephemeral arg to attack automation.
`-attackroll <value>` will replace the normal d20 part of the roll with a fixed number, keeping all other modifiers.

Add forced rolls as ephemeral arg to attack

---

aliasing/api/character.py
cogs5e/gametrack.py
cogs5e/models/sheet/player.py

Resolves AFR-921 (not on GitHub)
Add an `initial_value` kwarg to `create_cc_nx` and the respective internal object. Also adds the `-value` flag for `!cc create`.

Allow setting initial value during cc creation

---

.gitignore

The `.gitignore` hardcodes 2 cache directories, this changes it to instead filter `/.*cache/`, in order to catch more directories like `/.mypy_cache/`

Ignore more cache directories in .gitignore

---

cogs5e/sheets/errors.py
cogs5e/sheets/gsheet.py

Adds some more helpful errors to the gsheet importer/updater, to help users in identifying and fixing issues with their own sheet. Specifically, this adds the specific cell and worksheet name to the missing attribute error, and adds additional errors specifically for issues with attack parsing, coins import, and a basic validator for the portrait URL. The last one was particularly important to me, as it previously wouldn't error on import, but would cause issues when the user ran any command that would display their portrait.
Additionally, updates the message about private sheets to use the bots google service email (including locals/forks), and add a note about simply making the sheet available to anyone with a link.
Resolves #1289

Improve gsheet import error messages

---

cogs5e/utils/help_constants.py

I added `-mc` to `!help save` as it's not currently in the help text despite existing as an argument.

Adding `-mc` to `!help save` as it's currently missing.

---

cogs5e/models/automation/effects/attack.py
cogs5e/utils/help_constants.py

Add minimum attack roll handling arg with `-ma #` to not conflict with `-mi #` damage minimum
Resolves #AFR-891
When combined with #1740

Add minimum attack roll handling arg

---

aliasing/api/character.py
cogs5e/gametrack.py
cogs5e/models/automation/effects/attack.py
cogs5e/models/sheet/coinpurse.py
cogs5e/sheets/dicecloud.py
cogs5e/sheets/gsheet.py
cogs5e/utils/gameutils.py
docs/aliasing/api.rst
tests/cogs5e/models/automation/effects_test.py
tests/utiltests/coinpurse_test.py

Fixes a number of issues with the 3.4.0 patch:
- Adds docs for ``AliasCoinpurse[cointype]`` and ``str(AliasCoinpurse)``
- Fix an import error if a Gsheet 2.1 user renamed/deleted their 'Inventory' worksheet
- Reorder the coinpurse api docs slightly
- Slight rewording on the autoconvert help
- Strip comma's out on ``parse_coin_args`` to handle if the user had used digit grouping
- Fixed a minor typo in the helps for ``!game hp`` and ``!game thp`` 
- Make ``-attackroll 1`` count as a critical failure
- Handle the conversion of higher coins to lower when autoconverting
- Fix a race condition in entity reference tests
- Fix a small regex problem with Dicecloud coin import

Bugfixes for Coinpurse and -attackroll

---

cogs5e/models/automation/effects/attack.py
docs/automation_ref.rst

This PR adds support for automation attack effects to have inherent advantage, as well as adds a metavar for whether the last attack had advantage or not (``lastAttackHadAdvantage``).
Ties in with https://github.com/avrae/avrae-service/pull/47 and https://github.com/avrae/avrae.io/pull/640
Implements AFR-931

Inherent Attack Advantage and lastAttackHadAdvantage metavar

---

cogs5e/gametrack.py
cogs5e/utils/gameutils.py
tests/utiltests/coinpurse_test.py
ui/charsettings.py
utils/enums.py
utils/settings/character.py

This adds a csetting for how the user wants to handle autoconverting of coins if they attempt to remove more coins of explicit types than they currently have. Defaults to Always Ask, but has option for Never Convert and Always Convert.

Add Csetting for Coins Autoconvert

---

cogs5e/dice/cog.py

Simple clean up that makes all the functions in cog.py use the helper function embed_for_monster

Make these all use embed_for_monster

---

cogs5e/models/automation/__init__.py
cogs5e/models/automation/effects/damage.py
cogs5e/models/automation/runtime.py
cogs5e/models/automation/utils.py
cogs5e/utils/actionutils.py
gamedata/spell.py
ui/servsettings.py
utils/enums.py
utils/settings/guild.py

Adds two alternative crit damage types, with a selector in servsettings.
"Double Dice Amount", or RAW, doubles the amount of dice rolled (``2d8 + 4`` -> ``4d8 + 4``). 
"Add Max Dice Value", or Crunchy Crits, will add the maximum value of each die to the total (``2d8 + 4`` -> ``2d8 + 4 + 16``). 
"Double Total", will double everything (``2d8 + 4 -> (2d8 + 4) * 2``).
"Double Dice Total", or Mercer Crits, will double the total value of the dice rolled (``2d8 + 4`` -> ``(2d8) * 2 + 4``)
Resolves https://github.com/avrae/avrae/issues/875

Add Critical Damage Type Server Settings

---

cogs5e/lookup.py
cogs5e/sheetManager.py

Now consumes the command sent for monimage, monster, and token lookup if -h is passed

Add command consume to monimage, monster, and token

---

utils/functions.py

The bot was saving the entire avatar URL to the database, while the website was doing just the key. This changes it to the key in order to match how the website (which actually uses this information) handles it.
https://github.com/avrae/avrae-service/pull/48

Switch from using avatar url to the avatar key

---

cogs5e/initiative/cog.py

Currently the three commands that add to initiative use non-strict get_combatant() to see if a combatant already exists with their name, which means if someone joins with the name "Daniel", any attempts to add a combatant with a subset of the characters in Daniel ("D", "Dan", "niel", "ani", etc) returns the error "Combatant already exists". This switches those three commands to use strict mode, which only matches against exact case-insensitive names.

Use strict get_combatant

---

cogs5e/models/automation/effects/damage.py
cogs5e/utils/help_constants.py

This PR adds an arg for automation that rolls the damage dice twice, taking the higher of the two. This is primarily for things like Savage Attacker or the Butchers Bib.
This has been requested/discussed in the past (though the only formal request I can find is from [2018](https://discord.com/channels/269275778867396608/297190603819843586/456240614137135105), but likely due to the feat being viewed as 'mathematically bad' by the D&D community, it never saw much support, so we've mostly resolved to telling users the best option is to have two attacks, one with the damage 'advantage' and one without.

Add support for 'Savage Attacker' feat

---

aliasing/api/functions.py
aliasing/evaluators.py
docs/aliasing/api.rst

This PR solves AFR-850 by exposing the Random function random.choices() which allows for the creation of lists of arbitrary length when given an itterable, a desired length, and either weighted odds or cumulative weighted odds

Expose random.choices()

---

aliasing/api/functions.py

Fixes #1757
Changes the line using `max(..., key=...)` to `max(map(..., ...)`, because the former does not return the list of lengths, while the latter does.
I have not pulled this down to test it, however given how simple of a change it is, I don't expect it to run into issues.

fix: use max(map(...)) instead of max(..., key=...) in randchoices

---

README.md
cogs5e/initiative/cog.py
cogs5e/initiative/effects/passive.py
cogs5e/models/automation/effects/__init__.py
cogs5e/models/automation/effects/check.py
cogs5e/models/automation/effects/ieffect.py
cogs5e/models/automation/effects/remove_ieffect.py
cogs5e/models/automation/effects/save.py
cogs5e/models/automation/results.py
cogs5e/models/automation/runtime.py
cogs5e/models/homebrew/bestiary.py
cogs5e/sheetManager.py
cogs5e/utils/checkutils.py
cogs5e/utils/help_constants.py
docs/automation_ref.rst
requirements.txt
tests/cogs5e/models/automation/effects_test.py
utils/functions.py

Because that PR wasn't already large enough.
*Documentation*
- Rewrote the introduction to Automation Reference to provide a glossary
- Added documentation for the Check automation node
*Automation*
- Added the `ieffect` metavar to the runtime builtins when executing automation granted by an initiative effect
- Added the Check node to make ability checks, optionally against a DC or as a contest against the caster
- Fixed the Remove IEffect node not returning anything
- Added the `adv` key to Check and Save nodes
*IEffects*
- Added `-cadv` and `-cdis` to specify advantage/disadvantage on certain checks
*Other*
- Use the `automation-common` org lib to add additional validation to `!a import` and `!bestiary import`

Add more things to the IEffect Rewrite

---

aliasing/helpers.py

Improves the display of tracebacks in user aliases.

feat: tracebacks for draconic errors

---

cogs5e/initiative/cog.py
utils/functions.py

This changes how monster combatants are named when they are added to combat. There are two scenarios:
1. If the monster's name has multiple words/phrases, it will join together the first letter of each word, appending a number to make it unique: 
- ``Will-o'-Wisp`` -> ``WoW1``
- ``Monastery of the Distressed Body, Grand Master`` -> ``MotDBGM1``
2. If the monsters name only contains a single word, it will take the first two letters of their name, capitalize it, and then append a number to make it unique:
- ``Goblin`` -> ``GO1``
- ``Orc`` -> ``OR1``
This should help reduce ambiguity when adding groups of similar monsters together. For instance, in the old system, fighting a group of 10 Goblins and a Goblin Boss left you with ``GO1`` - ``GO11``. With this new system, it'll be ``GO1`` - …

Use initials for combatant names

---

cogs5e/initiative/effects/effect.py

Adds an additional check to the remaining property. This is the cause of this error from aliases.
After patch:

fix(effects): add additional check

---

tests/utiltests/argparser_test.py
utils/argparser.py

As of currently, to add a context to a ParsedArguments object based on a dict, you would need to create a temporary ParsedArguments object in a way which was harder to read.
This has the `add_context` method internally convert the dictionary into the correct ParsedArguments object without it needing to be done on the user's side.

feat(argparser): make add_context accept dicts

---

cogs5e/initiative/cog.py

Adds an option to `!init meta` to allow for a DM to change the combat's dm_id, which is used in `!i n`
Resolves #1775 (AFR-939)

Allow change of Combat DM

---

cogs5e/initiative/cog.py

fix(initiative): Error message reports whose spellbook the spell wasn't found in. Resolves AFR-811
Changed error message in "Spell not found in combatant's spellbook" to list the name of the combatant instead.

fix(initiative): Error message reports whose spellbook the spell wasn't found in

---

cogs5e/initiative/cog.py

Adds a new function to check if the monster id is in a set of specific exceptions, returning the first two letters if it is.
This is to handle cases where certain monster names, when initialized, results in unfortunate phrases.

Handle Monster Name Exceptions

---

cogs5e/initiative/buttons.py
cogs5e/initiative/effects/interaction.py
cogs5e/models/automation/effects/target.py
cogs5e/models/automation/runtime.py

Adds the 'ieffect' metavar to attacks granted by ieffects. 
Adds an parameter to determine if the automation was from a button or not.

Add the 'ieffect' metavar to attacks granted by ieffects

---

cogs5e/models/sheet/attack.py

Currently, LegacyIEffects using the `-attack` format fails to create auto-hit (`-attack '|<damage>|<details>'`) or no damage (`-attack '<to hit>||<details>'`) attacks. This broke many spells/actions/monster attacks as well as a lot of user effects that haven't been updated to IEffect2
Resolves #1799

Handle auto hit and no damage old -attack ieffects

---

cogs5e/models/automation/__init__.py

When adding support for ieffect granted attacks to use the ieffect metavar, I missed a spot where I needed to add `from_button`, which caused all buttons to break.

Fix Initiative Buttons

---

cogs5e/initiative/combat.py
cogs5e/models/character.py

This reverts commit bf2505f9ea395ec972dece6d1a7fc876b1bff8b4, fixing the character shard desync issue that cropped up over the weekend.

Revert "chore: use weakdict for combat/char memcache"

---

cogs5e/models/sheet/coinpurse.py

One of the errors for coinpurse says 'numeric' instead of 'integer'

Clarify coinpurse error

---

.github/workflows/approve-gamedata-test.yml
.github/workflows/test-data.yml
tests/README.md

It's really difficult to get GH to set secrets on a 3rd party PR (for good reason!). This updates the build so that a comment `/ci-approve` from a contributor with with write access on a PR triggers the gamedata test suite via a repository dispatch.

build: yet another attempt to approve 3pp gamedata prs

---

aliasing/evaluators.py
docs/aliasing/api.rst

Allows aliases/snippets to import modules defined in gvars using the new `using()` function.
Adds documentation on imports and module-writing.
Depends on https://github.com/avrae/draconic/pull/17

Add imports to aliasing

---

cogs5e/dice/inline.py
cogs5e/gamelog/cog.py
cogs5e/models/ddbsync.py
cogs5e/sheetManager.py
cogsmisc/core.py
cogsmisc/tutorials/__init__.py
dbot.py
tests/mocks.py
ui/charsettings.py
ui/servsettings.py
utils/checks.py
utils/feature_flags.py

Adds wrappers around `AsyncLaunchDarklyClient.variation` in order to make the two different methods for getting feature flag values for Discord/DDB users more consistent.

refactor: utility wrappers for feature flags

---

aliasing/evaluators.py

Change `uvar_exists` and `set_uvar_nx` from using `names` to `_cache['uvars']`
Fixes #AVR-931

fix(aliasing): uvar cache is used instead of names

---

docs/aliasing/api.rst

Adds documentation for Draconic try-except. Depends on https://github.com/avrae/draconic/pull/21.

docs(aliasing): try-except

---

aliasing/evaluators.py

A YAML Loader needs to have `inf_value` defined as a property in order to know what to load `.inf`. The only infinity we have available to use in Draconic is float infinity so I felt that DraconicLoader should have it be defined as such.
Currently the evaluator just errors when trying to load `.inf`.

fix(aliasing): allow load_yaml to load .inf

---

aliasing/api/statblock.py
cogs5e/initiative/combat.py

Hotfix to fix the issue with my fix for ``turnnotif`` not pinging the next combatant. Disnake expects a list with no duplicate items and not a set.

Fix duplicate id existing for turn notif

---

aliasing/api/statblock.py
cogs5e/models/sheet/resistance.py
tests/unit/resistance_test.py

Adds `Resistances.is_[resistant/immune/vulnerable/neutral](damage_type: str)` and respective AliasResistances methods to make finding out whether a target is resistant to a damage type string easier.

add AliasResistances util methods to find canonical resistance to str

---

cogs5e/utils/actionutils.py

Only check the first three letters and case desensitize `with` arg input for `!cast`, similar to what `!save` does for its input.

fix(cast): broaden acceptable with arg input

---

cogs5e/lookup.py
cogsmisc/tutorials/__init__.py
dbot.py
gamedata/lookuputils.py
gamedata/shared.py

- Adds slash commands to the various lookup commands.
- Ensures that entitlements are validated against and enforced on lookup, and works for homebrew as well.
- Caches a minimal version of monsters, spells, and items to reduce load for servers with a lot of homebrew.
- Allows the user to search by source slug (`/lookup subclass tcoe`) or by homebrew (`/lookup monster homebrew`)
- This won't purely limit the results, but will focus it down more

Lookup Slash Commands

---

cogs5e/models/dicecloud/autoparser.py
cogs5e/sheetManager.py
cogs5e/sheets/dicecloudv2.py

Reset types that are non-standard (events that do not coincide with long or short rest) now default to None, rather than raising an error.
Errors in action parsing now show both the action/spell and the property that caused the error (before it would just show the action/spell because the exception kept getting reraised with the new parent property)
If an action is tagged with `avrae:no_import` then it will not be imported or parsed, and if it's tagged with `avrae:parse_only` then it will not be attempted to be loaded from compendium, only parsed.

DCv2 post launch touch ups

---

cogs5e/models/embeds.py
cogsmisc/tutorials/models.py
dbot.py
gamedata/lookuputils.py
gamedata/monster.py
requirements.txt
tests/conftest.py
tests/utils.py
utils/config.py
utils/functions.py

Discord's API updated earlier tonight to have stricter type enforcement on Falsey values, which broke a number of base commands and a significant amount of user aliases. This updates Avrae to the newest 2.7.0 version of Disnake, which supports that API change. 
In addition to changes required to handle those Falsey values, the library update also changed the `AutoShardedBot` class to not use `**kwargs`, and so this also updates the code to use specific kwargs in the `super().__init__()` and not just star unpacking all of them.

Jan 9th Hotfix

---

cogs5e/models/automation/effects/roll.py

Allows RollEffectMetaVars to be operated on directly with pythonic operations, making automation simpler to import and write.

RollEffectMetaVars can have unop and binops applied

---

cogs5e/models/dicecloud/autoparser.py
cogs5e/sheetManager.py
cogs5e/sheets/dicecloudv2.py

Instead of raising an exception if no variable name is found for a skill, just skip it.
The value of the summary of notes should be used, rather than just the summary, as it is a dict, but we want a string.
Effects that have no value are returned as None rather than 0, so we should be sure to recognize these and skip them when they crop up.
Features and spells should also be taggable with no_import, so that features such as Crimson Rite doesn't end up importing all of the separate features.

DCv2, a few more problems

---

cogs5e/sheets/dicecloudv2.py

Would you look at that, it's another DCv2 PR, this one skips consumables that have undefined variable names, avoiding errors when you try to access the variable name.
I also added another debug point because it helps to know what action is causing the issue for quick workarounds.

fix(dcv2): skip resources that are undefined

---

cogs5e/models/sheet/coinpurse.py
tests/unit/coinpurse_test.py

Sometimes the convert methods would be off by 1cp due to floating point rounding errors; this makes them all operate using integer arithmetic. I haven't tested this locally but I did add a unit test for one random coinpurse that did make it round (encountered in the wild).

Fix edge case rounding error in coinpurse autoconvert methods

---

aliasing/api/character.py
aliasing/api/statblock.py

Change ValueError's to AttributeErrors to fix an issue with the Starred operator
The issue apparently existed beforehand, when going to assign either `AliasSkills` or `AliasCoinpurse` inside of a tuple, list, etc, but the Starred operator causes it to break if either was in a multiassignment as well, making it a much more noticeable and prevalent issue.

Feb 22, 2023 Hotfix

---

cogs5e/initiative/combatant.py

Fix health display for combatants with negative max hp

Fix health display for combatants with negative max hp

---

cogs5e/models/dicecloud/autoparser.py
cogs5e/sheets/dicecloudv2.py
setup.cfg

Completely overhaul Dicecloud V2's AutoParser, allowing more complex behaviours to be properly captured, like hit and miss effects, proper saving throws, conditional effects, and even indexed lists of effects.
Also includes a setup.cfg to make flake8 and pycodestyle respect line length.

Improvements to Dicecloud V2's AutoParser

---

cogs5e/sheets/dicecloudv2.py

On a generic error, second get_ident call should use atk_prop like the other errors

Slight issue in DCV2 import error display

---

cogs5e/initiative/combatant.py

Fixes the issue that prevented base AC setting effects from reducing the base ac
Changed the combatant AC determination to use the effect's base ac if it is present, rather than using the higher of the effect's base ac, and the combatant's natural base.

addressing issue regarding AC setting effects

---

cogs5e/models/automation/effects/save.py

- Move DC Bonus adding to after checking if they have a DC
- If its a spell using the default DC, and the user is not a spellcaster, this was causing an error before it would check of the DC was None
Plan to go live with this PR is at 10pm MT, June 14th

June 14th Hotfix

---

aliasing/api/combat.py
cogs5e/initiative/combat.py
cogs5e/initiative/combatant.py
cogs5e/initiative/effects/effect.py
cogs5e/initiative/group.py
cogs5e/models/automation/effects/ieffect.py
docs/automation_ref.rst

Allows initiative effects to tick on other combatants' turns, not just the combatant who the effect is on.
This makes durations of the form "until the caster's next turn" much easier to implement without having to deal with parent effects.
- IEffect: added `tick_on_caster`
- aliasing: added `tick_on_combatant_id` to `SimpleCombatant.add_effect()`
Depends on https://github.com/avrae/automation-common/pull/7.
Rather than 2 discrete hooks `Combatant.on_turn()` and `Combatant.on_turn_end()` checking only the effects of that combatant, the combat now runs the `on_turn()` hook for all combatants on every turn. `on_turn_end()` was removed, since effects that ticked on end of turn can now check if a combatant after it just began.

feat: ieffects tick on other combatant's turn

---

cogs5e/models/automation/effects/check.py
cogs5e/utils/help_constants.py

Adding "self" arguments for caster in contested vs. caster checks

Update check.py to allow for self-related arguments for "check vs caster" automation

---

cogs5e/models/automation/utils.py
cogs5e/utils/help_constants.py

Removes the check for if an automation call is a spell to use cantrip level dice, allowing normal actions to use it as intended.
Adds -cantripdice to override the amount of dice used by automation that calls for cantrip scaling, and can be used to go above  the normal 4 limit, allowing additional support for epic level homebrew. (something i had inquired about potentially requesting at one point.)

Added -cantripdice and fixed bug with cantrip scaling actions

---

gamedata/compendium.py
utils/redisIO.py

To address the MongoDB (DocumentDB) document size limitation for Monster Data, we considered various solutions, including migrating static files to S3, transitioning to a traditional relational database, or maintaining MongoDB using the GridFS client supplied by Mongo.
In alignment with our commitment to maintaining continuity for our community members operating their own Avrae instances, we've opted to retain data within MongoDB. This will be achieved through GridFS, with the flexibility of LaunchDarkly feature flags. These flags ensure that our users can choose whether to adopt GridFS for their needs, preserving flexibility and choice within the Avrae experience.

Add GridFS functionality via LaunchDarkly Flag

---

cogs5e/gamelog/cog.py
cogsmisc/customization.py

Discord made a change so that embeds sent with more than 25 fields will no longer trim the excess fields, but instead error. 
While we do have pagination set up on most things, at least for alias/snippet lists its set to paginate based on the number of collections displayed, as opposed to the number of fields. This is mostly fine, unless one collection has enough entries in it to go over the max field length, in which case we auto append a second field with a blank title, containing the rest (ad nauseum until all the data is covered).
This means if a user or server has 25+ collections, and at least one of those collections goes over the max field value size, an extra field gets added, and it sends the single page of 25 collections with 26+ fields. This was technically a bug for us before …

Quickfix for Alias/Snippet Pagination

---

requirements.txt

Currently avrae cannot retrieve server display names since discord changed its display name setup. [2.9.0 disnake apparently fixes this in 2.9.0](https://docs.disnake.dev/en/stable/whats_new.html#v2-9-0), so this PR upgrades to that version. 
Current behaviour: 
`!test {{verify_signature(signature()).author.display_name}}` falls back to the same result as `!test {{verify_signature(signature()).author.name}}` (username).
This change should allow server usernames to be accessible via the `verify_signature` function once more.

Uprev disnake to fix issue with display_name

---

utils/img.py

Image.ANTIALIAS is deprecated and removed in pillow 10 causing token utils to no longer be valid. The replacement for Image.ANTIALIAS is the IntEnum Resampling.LANCZOS, which Image.ANTIALIAS was an alias to previously. Also makes crop and resize into a single step by leveraging the box arg for img.resize
See [Pillow 9.1.0 update notes](https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html) for info about the deprecation.
Swap deprecated Image.ANTIALIAS for Image.Resampling.LANCZOS

Swap deprecated Image.ANTIALIAS for Image.Resampling.LANCZOS

---

cogs5e/models/homebrew/bestiary.py
cogs5e/utils/checkutils.py

Preserve ephemeral arguments in combat checks/saves by storing the arguments as a context, instead of overwriting the argument list directly.
Fixes AVR-978
Preserve ephemeral args in combat checks/saves (Fixed AVR-978)

fix: preserve ephem arguments in combat checks/saves

---

cogs5e/utils/checkutils.py

Corrects an issue with #1971 by making the combat context set `["True"]` instead of `True`, as `add_context` expects a list of strings and won't accept a direct value like setting it directly did.
Fix handling of cadv/cdis/sadv/sdis from ieffects

fix: properly handle cadv/cdis/sadv/sdis in arg context

---

cogs5e/models/homebrew/bestiary.py

This enables image imports from bestiary builder, which previously were accidentally left empty.

Enable image import from bestiary builder

---

aliasing/helpers.py
utils/argparser.py

- We parse raw arguments into a string, only to immediately split them back into a list once we get to argument parsing. Instead we should just return the list.
- argquote needs to match str.isspace, as otherwise we will split on characters that we are not quoting.
- Convert original_args to a string only once, since it won't change between accesses.
Improvements to snippet parsing

Improvements to snippet parsing

---

aliasing/helpers.py
cogs5e/dice/cog.py
cogs5e/gametrack.py
cogs5e/initiative/cog.py
cogs5e/lookup.py
cogs5e/sheetManager.py

Some commands being set up to receive a list of args from Disnake causes some issues with argparse, since Disnake only uses `"` for quoted strings, and as such the quote pairs that argsplitter and by extension argparse will not be used. Switching all of these commands to take a raw arg string from Disnake, and parse entirely using argparse resolves this issue.
Allow quote pairs to work everywhere argparse is used.

Allow quote pairs to work everywhere argparse is used

---

cogs5e/models/automation/runtime.py
cogs5e/utils/actionutils.py

Implements existing behavior in actions to include actions taken outside of initiative. This PR adds the "Damage taken" footer. The style of the message is modeled after the existing message when a creature with no HP (ex: added via `!i add`) is damaged.
Corrects an issue that prevented actions without automation from displaying a footer showing there was no automation.
- Corrects an issue that prevented actions without automation from displaying a footer showing there was no automation.
- Actions that have Damage nodes will now show a footer of the damage dealt when out of combat

Add damage information to non-init attacks

---

cogs5e/sheets/gsheet.py

At some point between gspread 3.7.0 and 6.0.0, gspread moved auth information into a new `HTTPClient` class which `gspread.Client` wraps.
However `HTTPClient` also provides a method which does the exact same thing that the existing token refresh method does.
I haven't been able to fully test if it works, however logically it should, since the body of the function is the same, it's just in a different place.
Fix GSheet reauthentication issue.

fix(gsheets): use http_client login method

---

cogs5e/sheets/gsheet.py

gspread now raises a PermissionError if the client does not have access to the requested sheet, so we must handle it as well.
Need to access auth within http_client to get the email.

Fix exception handling for gsheets

---

docs/aliasing/api.rst

Enumerate, get_uvar, and get_svar all had optional args that weren't being displayed properly in docs.

Minor documentation fixes

---

cogs5e/models/automation/effects/castspell.py
cogs5e/models/automation/runtime.py
cogs5e/utils/actionutils.py
docs/automation_ref.rst
utils/argparser.py

Adds `spell_level` as an automation metavar.
Resolves #1998 
Adds `spell_level` as an automation meta-var when casting a spell.

Add spell_level as an automation variable

---

cogs5e/models/character.py

This will make it clearer what context is being switched

Add extra messages when set_active is called to make it clear what is being switched.

---

cogs5e/models/character.py
cogs5e/sheetManager.py

Switch to using embeds for any character switching/setting and add a -name parameter to server and channel commands.
Using embeds for char channel, char server and char commands
Add a -name parameter for server and channel commands.

Add a name parameter to server and channel commands

---

cogs5e/models/character.py
cogs5e/sheetManager.py

The cache wasn't being populated when a character was being added by name selection, so it'd make a cache error be thrown.

Add a method to allow adding to cache from sheetManager

---

cogs5e/models/character.py
cogs5e/sheetManager.py

Make `!char name` revert back to unsetting channel and server and setting global as active. This matches existing behavior for !char and extends based on channel 
This also changes implementation to just be passing messages for SetActiveResult, which simplifies code quite a bit.

Make `!char name` revert back to unsetting channel and server and setting global as active

---

cogs5e/sheetManager.py

Fix resetall and clean-up documentation referencing not passing in name and defaulting to a global character

Fix resetall and clean-up documentation referencing not passing in name and defaulting to a global character

---

utils/help.py

Uses a basic regex to replace the `!` in `!help` output to use whatever the current context's prefix.
There might be cases where this doesn't work as intended, I didn't check every single command.
`!help` on servers with an adjusted command prefix will now show you commands using that prefix.

Replace default prefix in help commands with context prefix

---

cogs5e/sheetManager.py

Updates `!save` to properly handle the `!save death [fail|success|reset]` subcommand passing again
Was originally implemented in https://github.com/avrae/avrae/pull/1918, but https://github.com/avrae/avrae/pull/1989 ended up breaking this unintentionally
`!save death [fail|success|reset]` will properly fail, succeed, or reset your death saves again, without rolling.

Fixes the argument passing for `!save death [args]`

---

aliasing/api/combat.py

Enables strict=True option for get_effect for aliasing.

AFR-1043 - Enables strict=True option for get_effect for aliasing

---

cogs5e/sheets/dicecloudv2.py

Handles exclude (nonmagical pizza) and include (magical pizza) tags for damage resistances/immunities/vulnerabilities
This should properly import as `nonmagical bludgeoning`
Added support for Include and Exclude tags on damage resistances/immunities/vulnerabilities for Dicecloud V2 characters

Handle exclude and include tags for DCv2 resistances

---

cogsmisc/tutorials/playingthegame.py

When `!save death` was changed to use a subcommand, the tutorial "Playing the Game" stopped detecting the command properly (It was looking for the `!save` command with `death` in its args.
Additionally, the tutorially _probably_ should have been pointing at `!game deathsave` in the first place.
Fixed the Death Save portion of the "Playing the Game" tutorial.

Fix "Playing the Game" tutorial for death saves

---

aliasing/api/combat.py
docs/requirements.txt

Updates the Sphinx version to 5.3.0, as it started to fail [building 3 1/2 months ago](https://readthedocs.org/projects/avrae/builds/24248282/)
Also fixed the `get_effect()` docstring, as it was breaking without the extra line break?
You can see a version with these changes here: https://avrae-croebh.readthedocs.io/en/latest/
Fix the ReadTheDocs build process

Fix the ReadTheDocs builds

---

cogs5e/initiative/cog.py

Currently `!init skipround` does not adhere to the deathdelete toggle.  This change will verify deathdelete is True prior to removing 0 hp combatants with `!init skipround`

skipround respecting deathdelete

---

cogs5e/sheets/dicecloudv2.py

Race and a couple other properties were unable to be located as Dicecloud V2 libraries migrate to using library tags in place of standard sheet tags, however Avrae uses these tags to find certain properties, as such we should use the libraryTags property in combination with the standard tags property to find these properties.
Dicecloud V2: Use library tags for finding certain properties

Use library tags for finding certain properties

---

gamedata/lookuputils.py

With the changes to fuzzy search, the match key generated for slash commands wasn't as close as it needs to be, causing some homebrew stuff to end up being de-prioritized when selected via slash command lookup.
Honestly surprised it was working as well as it was before this, haha.
Fixed homebrew content (Monsters, spells, items) being able to be looked up properly with slash commands

Fix homebrew lookup in slash commands

---

cogs5e/models/sheet/player.py

Since the evaluation step already converts the error type, we don't need to catch it here.

Do not catch Evaluation Error for CC reset by

---

cogs5e/lookup.py
gamedata/monster.py

Make monster embeds closer to source material.
- Alignment can be omitted
- Size/Type/Alignment line is italicized
- Trait/Action names are italicized and have a full stop instead of a colon
- Removed punctuation not present in books
- Changed "CR" to "Challenge" as it is in books
- XP is comma-separated
Note: I haven't done anything with how ability scores are displayed because Discord doesn't support markdown tables and the current solution seems good enough while that remains true.
Make monster embeds closer to source material.

Improve monster embeds

---

docs/automation_ref.rst

This doesn't exist. https://github.com/avrae/automation-common/blob/7c0b4783d99eac27139c422d7c1ebd31b3337e3a/automation_common/validation/models.py#L106
Fixes an error in the automation docs about the Target node

Correct mistake in automation reference

---

cogs5e/initiative/cog.py

Frankly it is absurd that this wasn't a thing years ago but someone's gotta do it
Adds AFR-1055 | An additional alias for `!init`: `!I`. Mobile devices often correct the lowercase `i` to `I` when attempting to use `!i`; this ensures that users won't have to go out of their way to `!alias I i`, or spend the extra three fingerstrokes for `!init`.
Mobile users rejoice! A new built-in alias for `!init`, **`!I`**, allows one to access `!init` commands with just one fingerstroke on phones that were correcting the lowercase `i` to an uppercase `I`.

Add AFR-1055

---

cogs5e/initiative/cog.py

Clarify the documentation on making one-off custom attacks to indicate that the attack needs to be named, the name can be anything, and "custom" is an argument. The previous wording was unclear about whether "custom" was a argument, or to be specified as the name of the attack; this hopefully improves that.
Clarify !init attack documentation about custom one-off attacks
Clarify !init attack documentation about custom one-off attacks

Update custom one-off !init attack docs to be clearer about syntax

---

cogs5e/lookup.py

This update adds two aliases to give the ability to run the !race and !racefeat commands with:
- !species
- !speciesfeat

species and speciesfeat aliases for race and racefeat

---

cogs5e/sheetManager.py

Inform users trying to import bestiaries with `!import` rather than `!bestiary import`. This is a common mistake people make.
Warn users trying to `!import` bestiaries to use `!bestiary import` instead.

Warn users trying to import bestiaries with `!import` rather than `!bestiary import`

---

cogs5e/lookup.py
cogsmisc/adminUtils.py

Updated !rules/!reference command to accept version as an argument.
Example: !rules Two-Weapon Fighting 2014
Where **Two-Weapon Fighting** is the name to search and **2014** is the version
Version defaults to 2024 if no version is passed.
Add versioning to the rule compendium lookups.

Avr 516 add rules reference code in avrae to handle versions

---

cogs5e/sheetManager.py
gamedata/lookuputils.py
ui/charsettings.py
ui/servsettings.py

This update adds a check to respect the flag "allow_character_override" when importing a character and performing spells lookups.

Implementing logic to respect allow_character_override

---

cogs5e/initiative/cog.py

Noticed this when someone pulled up the help for init meta and decided to maintain my legacy of nonsense small changes
Fixed a spelling issue in `!help init meta`

Fixed a spelling issue in init dyn argument

---

cogs5e/models/sheet/attack.py

Adds `list_display_override` to Attacks, matching how it works on Actions. Allows users to override the display of custom attacks, as well as allowing the override on attacks on officially automated monsters.
Reliant on https://github.com/avrae/automation-common/pull/11
Adds `list_display_override` to Attacks, matching how it works on Actions. Allows users to override the display of custom attacks, as well as allowing the override on attacks on officially automated monsters.

Add `list_display_override` to custom attacks

---

aliasing/api/context.py

Adds a list of AliasRole to AliasAuthor
Accounted for DMs
AliasRoles can now be accessed from `ctx.author.get_roles()`

AFR-1014: Add AliasRoles

---

Dockerfile
dbot.py
requirements.txt

Added datadog support for traces on avrae bot according to [AVR-294](https://wizardsofthecoast.atlassian.net/browse/AVR-294). ECS task definition update is pending from avrae-terraform repo or direct aws console update, since the ddagent container is not defined in the task definition and its resources must be upgraded to prevent it from breaking.

AVR-294 added datadog tracer

---

gamedata/lookuputils.py

Spell lookup were breaking when executed in DMs due to serv_settings being None. The issue occurred because serv_settings.allow_character_override was accessed without checking if serv_settings existed.
Added a safeguard to ensure serv_settings is not None before checking allow_character_override, as serv_settings is unavailable in DMs.

hotfix: spell lookup on DMs

---

utils/datadog.py

Traces were being sent with 'production' environment instead of 'live', that's because the datadog patches were using the ENVIRONMENT variable which overrides the dd_env variable configured at the ECS task definition.

fix: mapping datadog trace environment to live

---

cogs5e/dice/cog.py
cogs5e/gametrack.py
cogs5e/initiative/cog.py
cogs5e/lookup.py
gamedata/lookuputils.py
gamedata/shared.py

- Update `/spell` to be more version agnostic 
- Update `!spell` to respect server version and user input if specified
- Setup lambda functions in `!cast`, `!mcast`, `!rcast`, etc to respect lookup version
- Modify `/rule` lookup to have a version parameter and the converter function to swap back and forth. 

Rule and Spell Lookup Changes

---

cogs5e/models/sheet/attack.py
docs/automation_ref.rst

Allow `list_display_override` to be an annotated string
Should be paired with avrae/automation-common#12

Allow `list_display_override` to be an annotated string

---

gamedata/spell.py

Update homebrew loading to set `rulesVersion` to `""` instead of `None`

Add empty rulesVersion field to homebrew spell data

---

cogs5e/sheets/beyond.py

correction for spell preparedness
Dot notation should be used for class attributes when sorting spells by preparedness
fingers crossed this does it

use dot notation for class attributes

---

cogs5e/sheetManager.py

Validate version against "2014","2024" and apply default logic if it is not valid as if not supplied
Validate version against "2014","2024" and apply default logic if it is not valid as if not supplied
Send message to user that version supplied was invalid
Similar logic for when in DMs but with no message
Fix for AVR-1026 - validate version on import
- [ x] This PR fixes an issue.
- [ x] If code changes were made then they have been tested.

Fix for AVR-1026

---

cogsmisc/customization.py
ui/servsettings.py

Setup a readonly version of `!servsettings` if the user can't manage the guild. 
Resolves #AFR-1069
Dependent on #2151 to fix linting issue

Add readonly mode to server settings UI and update permissions check

---

cogs5e/sheets/beyond.py

Previously, the logic did not account for cases where the DC values were missing when comparing and prioritizing prepared spells. This update ensures that DC comparisons are only made when both values are present, preventing potential errors.

Fix spell preparation logic to properly compare DC values.  Thanks @Rev

---

cogs5e/sheets/beyond.py
cogsmisc/customization.py

Improve server settings menu readonly logic to handle exceptions, and do the old `admin_or_permissions` check rather than just permissions
Run black and submite `beyond.py` to make Lint leave me alone. 

Have the readonly check use `admin_or_permissions` rather than just a permission lookup

---

cogs5e/initiative/combatant.py
cogs5e/models/character.py
cogs5e/sheets/beyond.py
docs/automation_ref.rst

Adds caster to list_display_override for characters.
Motivation: Allow safe handling of retrieving character level.
This does not affect automation because AutomationContext overrides the caster variable at runtime.
- `caster` (of type `AliasStatBlock`) is now available in list display override.

Add caster to list_display_override

---

cogs5e/dice/inline.py
cogs5e/sheets/beyond.py
cogsmisc/customization.py
cogsmisc/publicity.py
cogsmisc/stats.py
docker-compose.ci.yml
docker-compose.yml
tests/README.md
tests/unit/quickstartTutorial_test.py
utils/argparser.py
utils/redisIO.py

- Cleans up a few warnings in the tests
- Adds documentation for running tests on docker (including `docker compose down` beforehand to prevent intermittent dice_test failures.
- removes version tag from docker compose (deprecated, shows a warning when it is present)
- adds `r` to some raw-format strings to reduce test warnings
- gate Publicity and Stat loops from running without a token or production env, respectively
- **Change redis close mechanic** from .close to .aclose (showed as deprecated in test warnings) (only important change to review)
none (not user facing)

Improve Local Test Docs

---

aliasing/api/combat.py

Fixes the documentation, which incorrectly states that `get_combatant()` can return a group. 
This is a follow-up to an issue brought up on Discord in November, where updating the docs like this was deemed to be the simplest change. Rev also suggested replacing L68 with `return None`.
The alternative would be to change the code in [cogs5e/initiative/combat.py](https://github.com/avrae/avrae/blob/nightly/cogs5e/initiative/combat.py) so L317 and L319 there iterate over `self.get_combatants(groups=True)`, but this might break things.
N/A

docs: get_combatant() doesn't return groups

---

docs/automation_ref.rst

Add missing runtime variable to automation docs

---

cogs5e/models/automation/runtime.py
cogs5e/models/character.py
cogs5e/models/sheet/attack.py

- fixes issues with multiple vars like: `{strengthMod}+{proficiencyBonus}`
This fixes the issue brought up on [discord here](https://discord.com/channels/269275778867396608/795769081282297928/1401962233638031390). 
Fixed attack bonus parsing for expressions with multiple bonus variables

fix: upgrade .strip("<>{}") to .replace

---

cogs5e/lookup.py
cogs5e/models/sheet/base.py
cogs5e/models/sheet/resistance.py
gamedata/monster.py

Multiple updates to make the monster lookup embed more closely resemble the 2024 style. Specifically:
- Initiative is now displayed next to AC, not as a skill. As part of this, `str(BaseSkills)` no longer includes initiative.
- Ability scores and save bonuses are now displayed in two code-block tables. These are inline fields so work nicely on mobile as well as desktop.
- Senses are reordered to just above Languages.
- The damage types in stringified Vulnerabilities, Resistances, and Immunities are title case. For now, this only applies to the final word, not any of the "only" or "except" words. For example, `nonmagical nonsilvered piercing` becomes `nonmagical nonsilvered Piercing`. I'd appreciate feedback on whether this is the right approach.
- "Challenge" shortened to "CR" and now …

Display Stat Blocks in 2024 Style

---

docs/cheatsheets/automation_quirks.rst

Update the [Additional Automation Support](https://avrae.readthedocs.io/en/stable/cheatsheets/automation_quirks.html) page to include the new `-choice` options added to Elemental Weapon and Destructive Wave.

docs: add documentation for the Elemental Weapon and Destructive Wave `-choice` options

---

.github/workflows/rollback-ecs-live.yml
.github/workflows/rollback-ecs-stg.yml

This pull request introduces two new GitHub Actions workflows for rolling back the Avrae ECS service to a previous task definition revision in both the live and staging environments. These workflows provide a manual way to quickly revert deployments by either specifying a revision or using the previous one by default.
Added GitHub Actions workflows to enable manual ECS service rollbacks for live and staging environments.
[ ] This PR is a code change that implements a feature request.
[ ] This PR fixes an issue.
[X] This PR adds a new feature that is not an open feature request.
[ ] This PR is not a code change (e.g. documentation, README, ...)
[ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
[ ] If code changes were made then they have been tested.
[ ] I have …

Adding workflows to manually rollback ECS task's if failed deploy

---

cogs5e/sheets/beyond.py

Fixed inconsistent spell duplicate handling between compendium and homebrew spells in D&D Beyond imports. Previously, homebrew spells would unconditionally overwrite existing spells with the same name, causing unprepared homebrew versions to replace prepared compedium versions. The fix unifies duplicate handling logic so both spell types follow the same rules for prioritizing prepared spells and comparing spell attack bonuses/DCs.
Fixed homebrew spells incorrectly overwriting prepared compendium spells during D&D Beyond character import.

fix: unify beyond sheet duplicate handling for compendium and homebrew spells
